import React, { useEffect, useMemo, useRef, useState } from "react";
import {
  makeEmptySurvey,
  makeQuestionByType,
  normalizeSurvey,
  frontendSurveyToBackend,
  SURVEY_QUESTION_TYPES,
  surveyQuestionCount,
  getProjectId,
  listFeedsFromBackend,
  listSurveysFromBackend,
  loadSurveyFromBackend,
  saveSurveyToBackend,
  deleteSurveyOnBackend,
  linkSurveyToFeedsOnBackend,
  getLinkedFeedIdsForSurveyFromBackend,
} from "../utils";

/* =========================
   Small helpers
   ========================== */

const EDITOR_PAGE_BREAK_TYPE = "page_break";

const QUESTION_TYPE_LABELS = {
  [SURVEY_QUESTION_TYPES.TEXT]: "Text",
  [SURVEY_QUESTION_TYPES.TEXTAREA]: "Long text",
  [SURVEY_QUESTION_TYPES.SINGLE]: "Single choice",
  [SURVEY_QUESTION_TYPES.MULTI]: "Multiple choice",
  [SURVEY_QUESTION_TYPES.DROPDOWN]: "Dropdown",
  [SURVEY_QUESTION_TYPES.MATRIX_SINGLE]: "Matrix (single)",
  [SURVEY_QUESTION_TYPES.MATRIX_MULTI]: "Matrix (multi)",
  [SURVEY_QUESTION_TYPES.BIPOLAR]: "Bipolar scale",
  [SURVEY_QUESTION_TYPES.SLIDER]: "Slider",
  [SURVEY_QUESTION_TYPES.INFO]: "Info text",
  [EDITOR_PAGE_BREAK_TYPE]: "Page break",
};

const INSERTABLE_TYPES = [
  SURVEY_QUESTION_TYPES.TEXT,
  SURVEY_QUESTION_TYPES.TEXTAREA,
  SURVEY_QUESTION_TYPES.SINGLE,
  SURVEY_QUESTION_TYPES.MULTI,
  SURVEY_QUESTION_TYPES.DROPDOWN,
  SURVEY_QUESTION_TYPES.MATRIX_SINGLE,
  SURVEY_QUESTION_TYPES.MATRIX_MULTI,
  SURVEY_QUESTION_TYPES.BIPOLAR,
  SURVEY_QUESTION_TYPES.SLIDER,
  SURVEY_QUESTION_TYPES.INFO,
  EDITOR_PAGE_BREAK_TYPE,
];

const INPUT_HEIGHT = 42;
const TOP_ROW_LABEL_HEIGHT = 18;

function makeEditorId() {
  return `editor_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`;
}

function clampInt(value, min, max, fallback) {
  const n = Number(value);
  if (!Number.isFinite(n)) return fallback;
  return Math.max(min, Math.min(max, Math.round(n)));
}

function normalizeLinkedFeedIds(input) {
  return Array.isArray(input) ? input.map(String).filter(Boolean) : [];
}

function makeSequentialValue(prefix, index) {
  return `${prefix}_${index + 1}`;
}

function makeNumericValue(index) {
  return String(index + 1);
}

function sanitizeQuestionId(value, fallback = "") {
  const cleaned = String(value ?? "")
    .trim()
    .toUpperCase()
    .replace(/\s+/g, "_")
    .replace(/[^A-Z0-9_]/g, "");
  return cleaned || fallback;
}

function sanitizeFreeformValue(value, fallback = "") {
  const cleaned = String(value ?? "")
    .trim()
    .replace(/\s+/g, "_")
    .replace(/[^\w-]/g, "");
  return cleaned || fallback;
}

function preserveEmptyOrSanitize(value, fallback = "") {
  if (value === "") return "";
  if (value === null || value === undefined) return fallback;
  return sanitizeFreeformValue(value, fallback);
}

function isQuestionIdAutoGenerated(value = "") {
  return /^(Q_\d+|Q_\d+_\d+|Q_\d{6,}|Q_[A-Z0-9]+|q_\d+|q_[A-Za-z0-9_-]+)$/.test(
    String(value || "").trim()
  );
}

function makeMatrixRowValue(questionId, index) {
  const base = sanitizeQuestionId(questionId);
  return base ? `${base}_${index + 1}` : makeSequentialValue("row", index);
}

function shouldAutoRewriteRowValues(question) {
  const type = question?.type;
  return (
    type === SURVEY_QUESTION_TYPES.MATRIX_SINGLE ||
    type === SURVEY_QUESTION_TYPES.MATRIX_MULTI ||
    type === SURVEY_QUESTION_TYPES.BIPOLAR
  );
}

function ensureChoiceArray(items = []) {
  return (Array.isArray(items) ? items : []).map((item, i) => ({
    value: preserveEmptyOrSanitize(item?.value, makeNumericValue(i)),
    label: String(item?.label ?? ""),
  }));
}

function ensureMatrixArray(items = [], prefix = "item") {
  const useNumericDefault = prefix === "col";

  return (Array.isArray(items) ? items : []).map((item, i) => ({
    value: preserveEmptyOrSanitize(
      item?.value,
      useNumericDefault ? makeNumericValue(i) : makeSequentialValue(prefix, i)
    ),
    label: String(item?.label ?? ""),
  }));
}

function ensureMatrixRowsFromQuestionId(items = [], questionId = "") {
  return (Array.isArray(items) ? items : []).map((item, i) => ({
    value: preserveEmptyOrSanitize(item?.value, makeMatrixRowValue(questionId, i)),
    label: String(item?.label ?? ""),
  }));
}

function ensureBipolarRowArray(items = [], questionId = "") {
  return (Array.isArray(items) ? items : []).map((item, i) => ({
    value: preserveEmptyOrSanitize(item?.value, makeMatrixRowValue(questionId, i)),
    left_label: String(item?.left_label ?? item?.label ?? "").trim(),
    right_label: String(item?.right_label ?? "").trim(),
  }));
}

function rewriteQuestionRowValues(question, nextQuestionId) {
  if (!shouldAutoRewriteRowValues(question)) return question;

  const nextId = sanitizeQuestionId(nextQuestionId, question?.id || "");
  if (!nextId) return question;

  return {
    ...question,
    rows: (Array.isArray(question?.rows) ? question.rows : []).map((row, i) => ({
      ...row,
      value: makeMatrixRowValue(nextId, i),
    })),
  };
}

function makeCopiedQuestionId(existingIds = [], sourceId = "") {
  const cleanSourceId = sanitizeQuestionId(sourceId, `Q_${Date.now()}`);
  const idSet = new Set((Array.isArray(existingIds) ? existingIds : []).map((x) => String(x || "").trim()));

  let nextId = `${cleanSourceId}_COPY`;
  if (!idSet.has(nextId)) return nextId;

  let counter = 2;
  while (idSet.has(`${cleanSourceId}_COPY_${counter}`)) {
    counter += 1;
  }

  return `${cleanSourceId}_COPY_${counter}`;
}

function reorderArray(list = [], fromIndex, toIndex) {
  const arr = [...list];
  if (
    fromIndex === toIndex ||
    fromIndex < 0 ||
    toIndex < 0 ||
    fromIndex >= arr.length ||
    toIndex >= arr.length
  ) {
    return arr;
  }

  const [moved] = arr.splice(fromIndex, 1);
  arr.splice(toIndex, 0, moved);
  return arr;
}

function isCountedQuestionType(type) {
  return type !== SURVEY_QUESTION_TYPES.INFO && type !== EDITOR_PAGE_BREAK_TYPE;
}

function slugifySurveyName(name = "") {
  return String(name || "")
    .trim()
    .replace(/\s+/g, " ")
    .slice(0, 80);
}

function deepClone(value) {
  return JSON.parse(JSON.stringify(value));
}

function makeCopiedSurveyName(name = "") {
  const base = slugifySurveyName(name || "Untitled Survey");
  return base.endsWith("(Copy)") ? base : `${base} (Copy)`;
}

function makeImportedSurveyName(name = "") {
  const base = slugifySurveyName(name || "Untitled Survey");
  return base.endsWith("(Imported)") ? base : `${base} (Imported)`;
}

function resetSurveyIdentityForCopy(sourceSurvey, { projectId, keepFeedLinks = true } = {}) {
  const normalized = normalizeSurvey(deepClone(sourceSurvey || {}));

  const copied = {
    ...normalized,
    survey_id: "",
    name: makeCopiedSurveyName(normalized.name),
    linked_project_id: projectId || "",
    linked_feed_ids: keepFeedLinks ? normalizeLinkedFeedIds(normalized.linked_feed_ids) : [],
    created_at: null,
    updated_at: null,
    version: 1,
    status: normalized.status || "draft",
    pages: (normalized.pages || []).map((page, pageIndex) => ({
      ...page,
      id: page?.id || `page_${pageIndex + 1}`,
      questions: (page.questions || []).map((q, qIndex) => {
        const cleanQ = normalizeQuestionForEditor(q, qIndex);

        return {
          ...cleanQ,
          _editorId: makeEditorId(),
          meta: cleanQ?.meta ? deepClone(cleanQ.meta) : {},
          visible_if: cleanQ?.visible_if ? deepClone(cleanQ.visible_if) : null,
        };
      }),
    })),
  };

  return buildSurveyPagesFromFlatQuestions(
    copied,
    flattenSurveyPagesForEditor(copied)
  );
}

function resetSurveyIdentityForImport(sourceSurvey, { projectId } = {}) {
  const normalized = normalizeSurvey(deepClone(sourceSurvey || {}));

  const imported = {
    ...normalized,
    survey_id: "",
    name: makeImportedSurveyName(normalized.name),
    linked_project_id: projectId || "",
    linked_feed_ids: [],
    created_at: null,
    updated_at: null,
    version: 1,
    status: "draft",
    trigger: normalized.trigger || "after_feed_submit",
    pages: (normalized.pages || []).map((page, pageIndex) => ({
      ...page,
      id: page?.id || `page_${pageIndex + 1}`,
      questions: (page.questions || []).map((q, qIndex) => {
        const cleanQ = normalizeQuestionForEditor(q, qIndex);

        return {
          ...cleanQ,
          _editorId: makeEditorId(),
          meta: cleanQ?.meta ? deepClone(cleanQ.meta) : {},
          visible_if: cleanQ?.visible_if ? deepClone(cleanQ.visible_if) : null,
        };
      }),
    })),
  };

  return buildSurveyPagesFromFlatQuestions(
    imported,
    flattenSurveyPagesForEditor(imported)
  );
}

/* =========================
   Rich text helpers
   ========================== */

function normalizeRichTextHtml(value) {
  const raw = String(value ?? "").trim();
  if (!raw) return "";

  const looksLikeHtml = /<\/?[a-z][\s\S]*>/i.test(raw);
  if (looksLikeHtml) return raw;

  const escaped = raw
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  return escaped
    .split(/\n{2,}/)
    .map((block) => `<p>${block.replace(/\n/g, "<br>")}</p>`)
    .join("");
}

function stripHtmlForEmptyCheck(html = "") {
  return String(html || "")
    .replace(/<br\s*\/?>/gi, "")
    .replace(/<\/p>\s*<p>/gi, "")
    .replace(/<[^>]*>/g, "")
    .replace(/&nbsp;/gi, " ")
    .trim();
}

function normalizeQuestionForEditor(q = {}, index = 0) {
  const type = q?.type || SURVEY_QUESTION_TYPES.TEXT;

  if (type === EDITOR_PAGE_BREAK_TYPE) {
    return {
      _editorId: q?._editorId || makeEditorId(),
      id: q?.id || `page_break_${index + 1}`,
      type: EDITOR_PAGE_BREAK_TYPE,
      text: "",
      required: false,
      choices: [],
      rows: [],
      columns: [],
      min: 1,
      max: 7,
      left_label: "",
      right_label: "",
      placeholder: "",
      visible_if: null,
      meta: q?.meta || {},
    };
  }

  const normalizedId = sanitizeQuestionId(q?.id, "");

  return {
    _editorId: q?._editorId || makeEditorId(),
    id: normalizedId,
    type,
    text: normalizeRichTextHtml(q?.text ?? ""),
    required: type === SURVEY_QUESTION_TYPES.INFO ? false : !!q?.required,
    choices: ensureChoiceArray(q?.choices),
    rows:
      type === SURVEY_QUESTION_TYPES.BIPOLAR
        ? ensureBipolarRowArray(q?.rows, normalizedId)
        : type === SURVEY_QUESTION_TYPES.MATRIX_SINGLE ||
            type === SURVEY_QUESTION_TYPES.MATRIX_MULTI
          ? ensureMatrixRowsFromQuestionId(q?.rows, normalizedId)
          : [],
    columns: ensureMatrixArray(q?.columns, "col"),
    min: Number.isFinite(q?.min) ? q.min : 1,
    max: Number.isFinite(q?.max) ? q.max : 7,
    left_label: String(q?.left_label ?? ""),
    right_label: String(q?.right_label ?? ""),
    placeholder: String(q?.placeholder ?? ""),
    visible_if: q?.visible_if || null,
    meta: q?.meta || {},
  };
}

function flattenSurveyPagesForEditor(survey) {
  const sourceSurvey =
    survey && typeof survey === "object" ? survey : makeEmptySurvey();

  const pages = Array.isArray(sourceSurvey.pages) ? sourceSurvey.pages : [];
  const flat = [];

  if (pages.length === 0) return [];

  pages.forEach((page, pageIndex) => {
    const questions = Array.isArray(page?.questions) ? page.questions : [];

    questions.forEach((q) => {
      flat.push(normalizeQuestionForEditor(q, flat.length));
    });

    if (pageIndex < pages.length - 1) {
      flat.push(
        normalizeQuestionForEditor(
          {
            _editorId: `editor_page_break_${pageIndex + 1}`,
            id: `page_break_${pageIndex + 1}`,
            type: EDITOR_PAGE_BREAK_TYPE,
          },
          flat.length
        )
      );
    }
  });

  return flat;
}

function buildSurveyPagesFromFlatQuestions(survey, items) {
  const safeSurvey =
    survey && typeof survey === "object" ? survey : makeEmptySurvey();

  const flatItems = Array.isArray(items) ? items : [];
  const existingPages = Array.isArray(safeSurvey.pages) ? safeSurvey.pages : [];
  const splitPages = [];
  let currentQuestions = [];

  flatItems.forEach((item) => {
    if (item?.type === EDITOR_PAGE_BREAK_TYPE) {
      splitPages.push(currentQuestions);
      currentQuestions = [];
    } else {
      currentQuestions.push(normalizeQuestionForEditor(item, currentQuestions.length));
    }
  });

  splitPages.push(currentQuestions);

  const pages = splitPages.map((questions, pageIndex) => {
    const existingPage = existingPages[pageIndex] || {};
    return {
      id: existingPage.id || `page_${pageIndex + 1}`,
      title: String(existingPage.title ?? ""),
      description: String(existingPage.description ?? ""),
      questions: questions.map((q, i) => normalizeQuestionForEditor(q, i)),
    };
  });

  return {
    ...safeSurvey,
    pages: pages.length
      ? pages
      : [
          {
            id: "page_1",
            title: "",
            description: "",
            questions: [],
          },
        ],
  };
}

function getQuestionList(survey) {
  return flattenSurveyPagesForEditor(survey);
}

function setQuestionList(survey, questions) {
  return buildSurveyPagesFromFlatQuestions(survey, questions);
}

function makePageBreakForEditor(index = 0) {
  return normalizeQuestionForEditor(
    {
      id: `page_break_${Date.now()}_${index}`,
      type: EDITOR_PAGE_BREAK_TYPE,
    },
    index
  );
}

function makeBackendQuestionFromType(type, index = 0) {
  if (type === EDITOR_PAGE_BREAK_TYPE) {
    return makePageBreakForEditor(index);
  }

  const base = makeQuestionByType(type);
  const fallbackId = sanitizeQuestionId(base?.id, `Q_${Date.now()}`);

  const question = {
    id:
      base?.id && !isQuestionIdAutoGenerated(base.id)
        ? sanitizeQuestionId(base.id, fallbackId)
        : `Q_${Date.now()}`,
    type,
    text: normalizeRichTextHtml(String(base?.text ?? base?.label ?? "")),
    required: type === SURVEY_QUESTION_TYPES.INFO ? false : !!base?.required,
    choices: [],
    rows: [],
    columns: [],
    min: Number.isFinite(base?.min) ? base.min : 1,
    max: Number.isFinite(base?.max) ? base.max : 7,
    left_label: String(base?.left_label ?? base?.min_label ?? ""),
    right_label: String(base?.right_label ?? base?.max_label ?? ""),
    placeholder: String(base?.placeholder ?? ""),
    visible_if: base?.visible_if || null,
    meta: base?.meta || {},
  };

  if (
    type === SURVEY_QUESTION_TYPES.SINGLE ||
    type === SURVEY_QUESTION_TYPES.MULTI ||
    type === SURVEY_QUESTION_TYPES.DROPDOWN
  ) {
    const source =
      Array.isArray(base?.choices) && base.choices.length
        ? base.choices
        : Array.isArray(base?.options)
          ? base.options.map((label, i) => ({
              value: makeNumericValue(i),
              label: String(label || ""),
            }))
          : [];

    question.choices = ensureChoiceArray(source);
  }

  if (
    type === SURVEY_QUESTION_TYPES.MATRIX_SINGLE ||
    type === SURVEY_QUESTION_TYPES.MATRIX_MULTI
  ) {
    const srcRows = Array.isArray(base?.rows) && base.rows.length ? base.rows : [];
    const srcCols = Array.isArray(base?.columns) && base.columns.length ? base.columns : [];
    question.rows = ensureMatrixRowsFromQuestionId(srcRows, question.id);
    question.columns = ensureMatrixArray(srcCols, "col");
  }

  if (type === SURVEY_QUESTION_TYPES.BIPOLAR) {
    const srcRows = Array.isArray(base?.rows) && base.rows.length ? base.rows : [];
    question.rows = ensureBipolarRowArray(srcRows, question.id);
  }

  return normalizeQuestionForEditor(question, index);
}

function buildSavedQuestion(q, index) {
  const cleanQ = normalizeQuestionForEditor(q, index);

  return {
    id: sanitizeQuestionId(cleanQ.id, `Q_${index + 1}`),
    type: cleanQ.type,
    text: cleanQ.text,
    description: "",
    required: cleanQ.type === SURVEY_QUESTION_TYPES.INFO ? false : !!cleanQ.required,
    choices:
      cleanQ.type === SURVEY_QUESTION_TYPES.SINGLE ||
      cleanQ.type === SURVEY_QUESTION_TYPES.MULTI ||
      cleanQ.type === SURVEY_QUESTION_TYPES.DROPDOWN
        ? ensureChoiceArray(cleanQ.choices)
        : [],
    rows:
      cleanQ.type === SURVEY_QUESTION_TYPES.BIPOLAR
        ? ensureBipolarRowArray(cleanQ.rows, cleanQ.id)
        : cleanQ.type === SURVEY_QUESTION_TYPES.MATRIX_SINGLE ||
            cleanQ.type === SURVEY_QUESTION_TYPES.MATRIX_MULTI
          ? ensureMatrixRowsFromQuestionId(cleanQ.rows, cleanQ.id)
          : [],
    columns:
      cleanQ.type === SURVEY_QUESTION_TYPES.MATRIX_SINGLE ||
      cleanQ.type === SURVEY_QUESTION_TYPES.MATRIX_MULTI
        ? ensureMatrixArray(cleanQ.columns, "col")
        : [],
    left_label: cleanQ.left_label || "",
    right_label: cleanQ.right_label || "",
    min: Number.isFinite(cleanQ.min) ? cleanQ.min : 1,
    max: Number.isFinite(cleanQ.max) ? cleanQ.max : 7,
    placeholder: cleanQ.placeholder || "",
    visible_if: cleanQ.visible_if || null,
    meta: cleanQ.meta || {},
    randomize_options: false,
  };
}

/* =========================
   Small icon/button helpers
   ========================= */

function TrashIcon({ size = 16 }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      aria-hidden="true"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="3 6 5 6 21 6" />
      <path d="M8 6V4a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v2" />
      <path d="M19 6l-1 14a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1L5 6" />
      <line x1="10" y1="11" x2="10" y2="17" />
      <line x1="14" y1="11" x2="14" y2="17" />
    </svg>
  );
}

function PlusIcon({ size = 15 }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      aria-hidden="true"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" y1="5" x2="12" y2="19" />
      <line x1="5" y1="12" x2="19" y2="12" />
    </svg>
  );
}

function CopyIcon({ size = 16 }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      aria-hidden="true"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  );
}

function BoldIcon({ size = 14 }) {
  return (
    <svg viewBox="0 0 24 24" width={size} height={size} aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M7 5h6a4 4 0 0 1 0 8H7z" />
      <path d="M7 13h7a4 4 0 0 1 0 8H7z" />
    </svg>
  );
}

function ItalicIcon({ size = 14 }) {
  return (
    <svg viewBox="0 0 24 24" width={size} height={size} aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <line x1="19" y1="4" x2="10" y2="4" />
      <line x1="14" y1="20" x2="5" y2="20" />
      <line x1="15" y1="4" x2="9" y2="20" />
    </svg>
  );
}

function ListIcon({ size = 14 }) {
  return (
    <svg viewBox="0 0 24 24" width={size} height={size} aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <line x1="8" y1="6" x2="21" y2="6" />
      <line x1="8" y1="12" x2="21" y2="12" />
      <line x1="8" y1="18" x2="21" y2="18" />
      <circle cx="4" cy="6" r="1" fill="currentColor" stroke="none" />
      <circle cx="4" cy="12" r="1" fill="currentColor" stroke="none" />
      <circle cx="4" cy="18" r="1" fill="currentColor" stroke="none" />
    </svg>
  );
}

function OrderedListIcon({ size = 14 }) {
  return (
    <svg viewBox="0 0 24 24" width={size} height={size} aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <line x1="10" y1="6" x2="21" y2="6" />
      <line x1="10" y1="12" x2="21" y2="12" />
      <line x1="10" y1="18" x2="21" y2="18" />
      <path d="M4 7V4l-1 1" />
      <path d="M3 10h1a1 1 0 0 1 0 2H3l2 2h-2" />
      <path d="M3 16h2a1 1 0 0 1 0 2H3m1-3v6" />
    </svg>
  );
}

function IconOnlyButton({
  onClick,
  title,
  danger = false,
  disabled = false,
  style = {},
  size = 16,
  children = null,
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      title={title}
      aria-label={title}
      disabled={disabled}
      style={{
        width: INPUT_HEIGHT,
        height: INPUT_HEIGHT,
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 8,
        border: `1px solid ${danger ? "#dc2626" : "#d1d5db"}`,
        background: "#fff",
        color: danger ? "#dc2626" : disabled ? "#9ca3af" : "#111827",
        cursor: disabled ? "not-allowed" : "pointer",
        padding: 0,
        lineHeight: 1,
        ...style,
      }}
    >
      {children || <TrashIcon size={size} />}
    </button>
  );
}

function DragHandle({ onDragStart, onDragEnd }) {
  return (
    <div
      draggable
      onDragStart={onDragStart}
      onDragEnd={onDragEnd}
      title="Drag to reorder"
      style={{
        width: INPUT_HEIGHT,
        height: INPUT_HEIGHT,
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 8,
        border: "1px solid #d1d5db",
        background: "#fff",
        cursor: "grab",
        fontSize: 15,
        color: "#6b7280",
        userSelect: "none",
      }}
    >
      ⋮⋮
    </div>
  );
}

function RequiredToggleButton({ active, onClick, disabled = false }) {
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      title={active ? "Required" : "Optional"}
      style={{
        height: INPUT_HEIGHT,
        minWidth: 92,
        padding: "0 12px",
        borderRadius: 8,
        border: `1px solid ${active ? "#4f46e5" : "#d1d5db"}`,
        background: active ? "#eef2ff" : "#fff",
        color: active ? "#4338ca" : disabled ? "#9ca3af" : "#111827",
        fontWeight: 600,
        cursor: disabled ? "not-allowed" : "pointer",
        whiteSpace: "nowrap",
      }}
    >
      {active ? "Required" : "Optional"}
    </button>
  );
}

function TopField({ label, children }) {
  return (
    <div>
      <div
        style={{
          fontSize: 13,
          fontWeight: 600,
          marginBottom: 4,
          height: TOP_ROW_LABEL_HEIGHT,
          lineHeight: `${TOP_ROW_LABEL_HEIGHT}px`,
        }}
      >
        {label}
      </div>
      {children}
    </div>
  );
}

/* =========================
   Reusable editors
   ========================= */

function TextInput({ value, onChange, placeholder, style }) {
  return (
    <input
      value={value ?? ""}
      onChange={(e) => onChange(e.target.value)}
      placeholder={placeholder}
      style={{
        width: "100%",
        height: INPUT_HEIGHT,
        padding: "8px 10px",
        borderRadius: 8,
        border: "1px solid #d1d5db",
        boxSizing: "border-box",
        ...style,
      }}
    />
  );
}

function NumberInput({ value, onChange, min, max, step = 1, style }) {
  return (
    <input
      type="number"
      value={value ?? ""}
      min={min}
      max={max}
      step={step}
      onChange={(e) => onChange(e.target.value)}
      style={{
        width: "100%",
        height: INPUT_HEIGHT,
        padding: "8px 10px",
        borderRadius: 8,
        border: "1px solid #d1d5db",
        boxSizing: "border-box",
        ...style,
      }}
    />
  );
}

function TextAreaInput({ value, onChange, placeholder, rows = 3, style }) {
  return (
    <textarea
      value={value ?? ""}
      onChange={(e) => onChange(e.target.value)}
      placeholder={placeholder}
      rows={rows}
      style={{
        width: "100%",
        padding: "8px 10px",
        borderRadius: 8,
        border: "1px solid #d1d5db",
        resize: "vertical",
        boxSizing: "border-box",
        ...style,
      }}
    />
  );
}

function SelectInput({ value, onChange, children, style, disabled = false }) {
  return (
    <select
      value={value}
      onChange={(e) => onChange(e.target.value)}
      disabled={disabled}
      style={{
        width: "100%",
        height: INPUT_HEIGHT,
        padding: "8px 10px",
        borderRadius: 8,
        border: "1px solid #d1d5db",
        background: "#fff",
        boxSizing: "border-box",
        ...style,
      }}
    >
      {children}
    </select>
  );
}

function FieldBlock({ label, children, hint = "" }) {
  return (
    <div style={{ marginBottom: 10 }}>
      <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 4 }}>{label}</div>
      {children}
      {hint ? (
        <div style={{ fontSize: 12, color: "#6b7280", marginTop: 4 }}>{hint}</div>
      ) : null}
    </div>
  );
}

function SectionCard({ title, children, right = null }) {
  return (
    <div
      style={{
        border: "1px solid #e5e7eb",
        borderRadius: 14,
        background: "#fff",
        padding: 16,
        marginBottom: 18,
        boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
      }}
    >
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          gap: 12,
          marginBottom: 12,
        }}
      >
        <h4 style={{ margin: 0, fontSize: 16 }}>{title}</h4>
        {right}
      </div>
      {children}
    </div>
  );
}

function RichToolbarButton({ title, onMouseDown, active = false, children }) {
  return (
    <button
      type="button"
      title={title}
      aria-label={title}
      onMouseDown={onMouseDown}
      style={{
        width: 32,
        height: 32,
        borderRadius: 8,
        border: `1px solid ${active ? "#4f46e5" : "#d1d5db"}`,
        background: active ? "#eef2ff" : "#fff",
        color: active ? "#4338ca" : "#111827",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        cursor: "pointer",
        padding: 0,
      }}
    >
      {children}
    </button>
  );
}

function RichTextEditor({ value, onChange, placeholder = "Question text" }) {
  const editorRef = useRef(null);
  const [focused, setFocused] = useState(false);
  const [formats, setFormats] = useState({
    bold: false,
    italic: false,
    insertUnorderedList: false,
    insertOrderedList: false,
  });

  const normalizedValue = normalizeRichTextHtml(value);

  useEffect(() => {
    const el = editorRef.current;
    if (!el) return;

    if (el.innerHTML !== normalizedValue) {
      el.innerHTML = normalizedValue || "";
    }
  }, [normalizedValue]);

  function updateFormats() {
    try {
      setFormats({
        bold: !!document.queryCommandState("bold"),
        italic: !!document.queryCommandState("italic"),
        insertUnorderedList: !!document.queryCommandState("insertUnorderedList"),
        insertOrderedList: !!document.queryCommandState("insertOrderedList"),
      });
    } catch {
      setFormats({
        bold: false,
        italic: false,
        insertUnorderedList: false,
        insertOrderedList: false,
      });
    }
  }

  function emitChange() {
    const el = editorRef.current;
    if (!el) return;

    const rawHtml = el.innerHTML || "";
    const textOnly = stripHtmlForEmptyCheck(rawHtml);

    if (!textOnly) {
      onChange("");
      return;
    }

    onChange(rawHtml);
  }

  function runCommand(command, commandValue = null) {
    const el = editorRef.current;
    if (!el) return;

    el.focus();

    try {
      document.execCommand(command, false, commandValue);
    } catch {}

    if (command === "formatBlock") {
      try {
        document.execCommand("defaultParagraphSeparator", false, "p");
      } catch {}
    }

    updateFormats();
    emitChange();
  }

  function handleInput() {
    emitChange();
    updateFormats();
  }

  function handlePaste(e) {
    e.preventDefault();
    const text = e.clipboardData?.getData("text/plain") || "";
    try {
      document.execCommand("insertText", false, text);
    } catch {
      const el = editorRef.current;
      if (!el) return;
      el.innerText = `${el.innerText || ""}${text}`;
    }
    emitChange();
    updateFormats();
  }

  const isEmpty = !stripHtmlForEmptyCheck(normalizedValue);

  return (
    <div
      style={{
        border: `1px solid ${focused ? "#4f46e5" : "#d1d5db"}`,
        borderRadius: 10,
        overflow: "hidden",
        background: "#fff",
        boxShadow: focused ? "0 0 0 3px rgba(79,70,229,0.10)" : "none",
      }}
    >
      <div
        style={{
          display: "flex",
          gap: 6,
          alignItems: "center",
          padding: 8,
          borderBottom: "1px solid #e5e7eb",
          background: "#fafafa",
          flexWrap: "wrap",
        }}
      >
        <RichToolbarButton
          title="Bold"
          active={formats.bold}
          onMouseDown={(e) => {
            e.preventDefault();
            runCommand("bold");
          }}
        >
          <BoldIcon size={14} />
        </RichToolbarButton>

        <RichToolbarButton
          title="Italic"
          active={formats.italic}
          onMouseDown={(e) => {
            e.preventDefault();
            runCommand("italic");
          }}
        >
          <ItalicIcon size={14} />
        </RichToolbarButton>

        <RichToolbarButton
          title="Bullet list"
          active={formats.insertUnorderedList}
          onMouseDown={(e) => {
            e.preventDefault();
            runCommand("insertUnorderedList");
          }}
        >
          <ListIcon size={14} />
        </RichToolbarButton>

        <RichToolbarButton
          title="Numbered list"
          active={formats.insertOrderedList}
          onMouseDown={(e) => {
            e.preventDefault();
            runCommand("insertOrderedList");
          }}
        >
          <OrderedListIcon size={14} />
        </RichToolbarButton>

        <RichToolbarButton
          title="Paragraph"
          onMouseDown={(e) => {
            e.preventDefault();
            runCommand("formatBlock", "p");
          }}
        >
          <span style={{ fontSize: 11, fontWeight: 700 }}>P</span>
        </RichToolbarButton>
      </div>

      <div style={{ position: "relative" }}>
        {isEmpty && !focused && (
          <div
            style={{
              position: "absolute",
              left: 12,
              top: 12,
              color: "#9ca3af",
              pointerEvents: "none",
              fontSize: 14,
            }}
          >
            {placeholder}
          </div>
        )}

        <div
          ref={editorRef}
          contentEditable
          suppressContentEditableWarning
          onFocus={() => {
            setFocused(true);
            updateFormats();
          }}
          onBlur={() => {
            setFocused(false);
            emitChange();
          }}
          onInput={handleInput}
          onKeyUp={updateFormats}
          onMouseUp={updateFormats}
          onPaste={handlePaste}
          style={{
            minHeight: 120,
            padding: 12,
            outline: "none",
            lineHeight: 1.5,
            fontSize: 14,
          }}
        />
      </div>
    </div>
  );
}

function InsertAtBorderButton({ position = "top", onInsert }) {
  const [open, setOpen] = useState(false);
  const [hovered, setHovered] = useState(false);
  const [selectedType, setSelectedType] = useState(SURVEY_QUESTION_TYPES.TEXT);
  const wrapRef = useRef(null);

  useEffect(() => {
    function handleClickOutside(e) {
      if (wrapRef.current && !wrapRef.current.contains(e.target)) {
        setOpen(false);
      }
    }

    function handleEscape(e) {
      if (e.key === "Escape") setOpen(false);
    }

    document.addEventListener("mousedown", handleClickOutside);
    document.addEventListener("keydown", handleEscape);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
      document.removeEventListener("keydown", handleEscape);
    };
  }, []);

  const isTop = position === "top";
  const isActive = hovered || open;

  return (
    <div
      ref={wrapRef}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{
        position: "absolute",
        left: "50%",
        transform: "translateX(-50%)",
        top: isTop ? -11 : "auto",
        bottom: !isTop ? -11 : "auto",
        zIndex: 6,
        pointerEvents: "auto",
      }}
    >
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        title={isTop ? "Insert above" : "Insert below"}
        style={{
          width: 22,
          height: 22,
          borderRadius: 999,
          border: "1px solid #d1d5db",
          background: "#fff",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          cursor: "pointer",
          padding: 0,
          boxShadow: isActive ? "0 1px 4px rgba(0,0,0,0.10)" : "none",
          opacity: isActive ? 1 : 0.4,
          transition: "opacity 0.15s ease, box-shadow 0.15s ease, transform 0.15s ease",
          transform: isActive ? "scale(1)" : "scale(0.96)",
        }}
      >
        <PlusIcon size={10} />
      </button>

      {open && (
        <div
          style={{
            position: "absolute",
            left: "50%",
            transform: "translateX(-50%)",
            top: isTop ? 28 : "auto",
            bottom: !isTop ? 28 : "auto",
            minWidth: 220,
            padding: 10,
            borderRadius: 10,
            border: "1px solid #d1d5db",
            background: "#fff",
            boxShadow: "0 10px 24px rgba(0,0,0,0.12)",
          }}
        >
          <div style={{ fontSize: 12, marginBottom: 6 }}>Add question</div>

          <SelectInput value={selectedType} onChange={setSelectedType}>
            {INSERTABLE_TYPES.map((t) => (
              <option key={t} value={t}>
                {QUESTION_TYPE_LABELS[t] || t}
              </option>
            ))}
          </SelectInput>

          <button
            type="button"
            onClick={() => {
              onInsert(selectedType);
              setOpen(false);
            }}
            style={{
              marginTop: 8,
              width: "100%",
              padding: "6px 8px",
              borderRadius: 6,
              border: "1px solid #d1d5db",
              background: "#fff",
              cursor: "pointer",
            }}
          >
            Add
          </button>
        </div>
      )}
    </div>
  );
}

function ItemTableEditor({
  title,
  items,
  onChange,
  prefix = "opt",
  addLabel = "Add row",
  valuePlaceholder = "Value",
  labelPlaceholder = "Label",
}) {
  const safeItems = Array.isArray(items) ? items : [];

  function updateItem(index, patch) {
    onChange(safeItems.map((item, i) => (i === index ? { ...item, ...patch } : item)));
  }

  function addItem() {
    const nextValue =
      prefix === "opt" || prefix === "col"
        ? makeNumericValue(safeItems.length)
        : makeSequentialValue(prefix, safeItems.length);

    onChange([
      ...safeItems,
      {
        value: nextValue,
        label: "",
      },
    ]);
  }

  function removeItem(index) {
    onChange(safeItems.filter((_, i) => i !== index));
  }

  const singularTitle =
    String(title || "item")
      .replace(/ \/ .*/g, "")
      .replace(/s$/i, "")
      .toLowerCase() || "item";

  return (
    <div
      style={{
        border: "1px solid #d1d5db",
        borderRadius: 10,
        padding: 10,
        background: "#fafafa",
      }}
    >
      <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 8 }}>{title}</div>

      {safeItems.length === 0 && (
        <div style={{ fontSize: 12, color: "#6b7280", marginBottom: 8 }}>No items yet.</div>
      )}

      <div style={{ display: "grid", gap: 8 }}>
        {safeItems.map((item, i) => (
          <div
            key={`${prefix}_${i}`}
            style={{
              display: "grid",
              gridTemplateColumns: "160px 1fr auto",
              gap: 8,
              alignItems: "center",
            }}
          >
            <TextInput
              value={item?.value ?? ""}
              onChange={(v) => updateItem(i, { value: v })}
              placeholder={valuePlaceholder}
            />
            <TextInput
              value={item?.label ?? ""}
              onChange={(v) => updateItem(i, { label: v })}
              placeholder={labelPlaceholder}
            />
            <IconOnlyButton
              onClick={() => removeItem(i)}
              title={`Delete ${singularTitle}`}
              danger
            />
          </div>
        ))}
      </div>

      <button
        type="button"
        onClick={addItem}
        style={{
          marginTop: 10,
          padding: "8px 10px",
          borderRadius: 8,
          border: "1px solid #d1d5db",
          background: "#fff",
          cursor: "pointer",
        }}
      >
        + {addLabel}
      </button>
    </div>
  );
}

function BipolarRowTableEditor({ items, onChange, questionId }) {
  const safeItems = Array.isArray(items) ? items : [];

  function updateItem(index, patch) {
    onChange(safeItems.map((item, i) => (i === index ? { ...item, ...patch } : item)));
  }

  function addItem() {
    onChange([
      ...safeItems,
      {
        value: makeMatrixRowValue(questionId, safeItems.length),
        left_label: "",
        right_label: "",
      },
    ]);
  }

  function removeItem(index) {
    onChange(safeItems.filter((_, i) => i !== index));
  }

  return (
    <div
      style={{
        border: "1px solid #d1d5db",
        borderRadius: 10,
        padding: 10,
        background: "#fafafa",
      }}
    >
      <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 8 }}>
        Rows / bipolar anchors
      </div>

      {safeItems.length === 0 && (
        <div style={{ fontSize: 12, color: "#6b7280", marginBottom: 8 }}>No rows yet.</div>
      )}

      <div style={{ display: "grid", gap: 8 }}>
        {safeItems.map((item, i) => (
          <div
            key={`bipolar_row_${i}`}
            style={{
              display: "grid",
              gridTemplateColumns: "160px 1fr 1fr auto",
              gap: 8,
              alignItems: "center",
            }}
          >
            <TextInput
              value={item?.value ?? ""}
              onChange={(v) => updateItem(i, { value: v })}
              placeholder="Value"
            />
            <TextInput
              value={item?.left_label ?? ""}
              onChange={(v) => updateItem(i, { left_label: v })}
              placeholder="Left label"
            />
            <TextInput
              value={item?.right_label ?? ""}
              onChange={(v) => updateItem(i, { right_label: v })}
              placeholder="Right label"
            />
            <IconOnlyButton onClick={() => removeItem(i)} title="Delete row" danger />
          </div>
        ))}
      </div>

      <button
        type="button"
        onClick={addItem}
        style={{
          marginTop: 10,
          padding: "8px 10px",
          borderRadius: 8,
          border: "1px solid #d1d5db",
          background: "#fff",
          cursor: "pointer",
        }}
      >
        + Add row
      </button>
    </div>
  );
}

/* =========================
   Question editor
   ========================= */

function QuestionActions({
  q,
  index,
  totalQuestions,
  moveQuestion,
  removeQuestion,
  duplicateQuestion,
  updateQuestion,
  onDragStart,
  onDragEnd,
}) {
  const isInfo = q?.type === SURVEY_QUESTION_TYPES.INFO;

  return (
    <TopField label="Actions">
      <div
        style={{
          display: "flex",
          gap: 6,
          alignItems: "center",
          height: INPUT_HEIGHT,
        }}
      >
        <DragHandle
          onDragStart={(e) => onDragStart(e, q._editorId)}
          onDragEnd={onDragEnd}
        />

        {!isInfo && (
          <RequiredToggleButton
            active={!!q.required}
            onClick={() => updateQuestion(index, { required: !q.required })}
          />
        )}

        <button
          type="button"
          onClick={() => moveQuestion(index, index - 1)}
          disabled={index === 0}
          style={smallActionButtonStyle(index === 0)}
        >
          ↑
        </button>

        <button
          type="button"
          onClick={() => moveQuestion(index, index + 1)}
          disabled={index === totalQuestions - 1}
          style={smallActionButtonStyle(index === totalQuestions - 1)}
        >
          ↓
        </button>

        <IconOnlyButton
          onClick={() => duplicateQuestion(index)}
          title="Copy question"
        >
          <CopyIcon size={16} />
        </IconOnlyButton>

        <IconOnlyButton
          onClick={() => removeQuestion(index)}
          title="Delete question"
          danger
        />
      </div>
    </TopField>
  );
}

function QuestionCard({
  q,
  index,
  displayNumber,
  totalQuestions,
  updateQuestion,
  removeQuestion,
  moveQuestion,
  duplicateQuestion,
  insertQuestionAt,
  draggingId,
  dragOverId,
  onDragStart,
  onDragOver,
  onDrop,
  onDragEnd,
}) {
  const type = q?.type;
  const isPageBreak = type === EDITOR_PAGE_BREAK_TYPE;

  const isChoice =
    type === SURVEY_QUESTION_TYPES.SINGLE ||
    type === SURVEY_QUESTION_TYPES.MULTI ||
    type === SURVEY_QUESTION_TYPES.DROPDOWN;

  const isMatrix =
    type === SURVEY_QUESTION_TYPES.MATRIX_SINGLE ||
    type === SURVEY_QUESTION_TYPES.MATRIX_MULTI;

  const isBipolar = type === SURVEY_QUESTION_TYPES.BIPOLAR;
  const isSlider = type === SURVEY_QUESTION_TYPES.SLIDER;

  const isDragging = draggingId === q._editorId;
  const isDragOver = dragOverId === q._editorId;

  const shellStyle = {
    position: "relative",
    border: isDragOver ? "2px solid #6366f1" : `1px solid ${isPageBreak ? "#9ca3af" : "#d1d5db"}`,
    borderStyle: isPageBreak ? "dashed" : "solid",
    borderRadius: 12,
    padding: 14,
    marginTop: 18,
    marginBottom: 26,
    background: isDragging ? "#f8fafc" : isPageBreak ? "#f9fafb" : "#fff",
    opacity: isDragging ? 0.65 : 1,
    boxShadow: isDragOver ? "0 0 0 3px rgba(99,102,241,0.12)" : "none",
  };

  if (isPageBreak) {
    return (
      <div
        onDragOver={(e) => onDragOver(e, q._editorId)}
        onDrop={(e) => onDrop(e, q._editorId)}
        style={shellStyle}
      >
        <InsertAtBorderButton
          position="top"
          onInsert={(nextType) => insertQuestionAt(index, nextType, "above")}
        />
        <InsertAtBorderButton
          position="bottom"
          onInsert={(nextType) => insertQuestionAt(index, nextType, "below")}
        />

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr auto",
            gap: 10,
            alignItems: "start",
          }}
        >
          <TopField label="Page break">
            <div
              style={{
                height: INPUT_HEIGHT,
                display: "flex",
                alignItems: "center",
                padding: "0 12px",
                border: "1px solid #d1d5db",
                borderRadius: 8,
                background: "#fff",
                color: "#6b7280",
              }}
            >
              Questions after this will appear on the next page.
            </div>
          </TopField>

          <TopField label="Actions">
            <div
              style={{
                display: "flex",
                gap: 6,
                alignItems: "center",
                height: INPUT_HEIGHT,
              }}
            >
              <DragHandle
                onDragStart={(e) => onDragStart(e, q._editorId)}
                onDragEnd={onDragEnd}
              />

              <button
                type="button"
                onClick={() => moveQuestion(index, index - 1)}
                disabled={index === 0}
                style={smallActionButtonStyle(index === 0)}
              >
                ↑
              </button>

              <button
                type="button"
                onClick={() => moveQuestion(index, index + 1)}
                disabled={index === totalQuestions - 1}
                style={smallActionButtonStyle(index === totalQuestions - 1)}
              >
                ↓
              </button>

              <IconOnlyButton
                onClick={() => removeQuestion(index)}
                title="Delete page break"
                danger
              />
            </div>
          </TopField>
        </div>
      </div>
    );
  }

  return (
    <div
      onDragOver={(e) => onDragOver(e, q._editorId)}
      onDrop={(e) => onDrop(e, q._editorId)}
      style={shellStyle}
    >
      <InsertAtBorderButton
        position="top"
        onInsert={(nextType) => insertQuestionAt(index, nextType, "above")}
      />
      <InsertAtBorderButton
        position="bottom"
        onInsert={(nextType) => insertQuestionAt(index, nextType, "below")}
      />

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "minmax(0,1fr) 220px auto",
          gap: 10,
          alignItems: "start",
          marginBottom: 10,
        }}
      >
        <TopField
          label={
            type === SURVEY_QUESTION_TYPES.INFO
              ? "Info text"
              : `Question ${displayNumber}`
          }
        >
          <RichTextEditor
            value={q.text || ""}
            onChange={(v) => updateQuestion(index, { text: v })}
            placeholder={
              type === SURVEY_QUESTION_TYPES.INFO ? "Info text" : "Question text"
            }
          />
        </TopField>

        <TopField label="Type">
          <SelectInput
            value={q.type}
            onChange={(nextType) => {
              if (nextType === EDITOR_PAGE_BREAK_TYPE) {
                updateQuestion(index, makePageBreakForEditor(index));
                return;
              }

              const next = makeBackendQuestionFromType(nextType, index);
              const preservedId = sanitizeQuestionId(q.id, next.id);

              let merged = {
                ...next,
                _editorId: q._editorId,
                id: preservedId,
                text: q.text || next.text,
                required: nextType === SURVEY_QUESTION_TYPES.INFO ? false : !!q.required,
                visible_if: q.visible_if || null,
                meta: q.meta || {},
              };

              if (shouldAutoRewriteRowValues(merged)) {
                merged = rewriteQuestionRowValues(merged, preservedId);
              }

              updateQuestion(index, merged);
            }}
          >
            {INSERTABLE_TYPES.map((t) => (
              <option key={t} value={t}>
                {QUESTION_TYPE_LABELS[t] || t}
              </option>
            ))}
          </SelectInput>
        </TopField>

        <QuestionActions
          q={q}
          index={index}
          totalQuestions={totalQuestions}
          moveQuestion={moveQuestion}
          removeQuestion={removeQuestion}
          duplicateQuestion={duplicateQuestion}
          updateQuestion={updateQuestion}
          onDragStart={onDragStart}
          onDragEnd={onDragEnd}
        />
      </div>

      <FieldBlock label="Question ID / variable name">
        <TextInput
          value={q.id || ""}
          onChange={(v) => {
            const cleanedId = sanitizeQuestionId(v, "");
            let nextQuestion = {
              ...q,
              id: cleanedId,
            };

            if (cleanedId && shouldAutoRewriteRowValues(nextQuestion)) {
              nextQuestion = rewriteQuestionRowValues(nextQuestion, cleanedId);
            }

            updateQuestion(index, nextQuestion);
          }}
          placeholder="e.g. AUTH"
        />
      </FieldBlock>

      {isChoice && (
        <ItemTableEditor
          title="Options"
          items={q.choices}
          onChange={(items) => updateQuestion(index, { choices: ensureChoiceArray(items) })}
          prefix="opt"
          addLabel="Add option"
        />
      )}

      {isMatrix && (
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr",
            gap: 12,
          }}
        >
          <ItemTableEditor
            title="Rows / items"
            items={q.rows}
            onChange={(items) =>
              updateQuestion(index, {
                rows: ensureMatrixRowsFromQuestionId(items, q.id),
              })
            }
            prefix={sanitizeQuestionId(q.id, "ROW")}
            addLabel="Add row"
            valuePlaceholder="Auto id"
            labelPlaceholder="Item text"
          />

          <ItemTableEditor
            title="Columns / scale points"
            items={q.columns}
            onChange={(items) =>
              updateQuestion(index, { columns: ensureMatrixArray(items, "col") })
            }
            prefix="col"
            addLabel="Add column"
            valuePlaceholder="Value"
            labelPlaceholder="Label"
          />
        </div>
      )}

      {isBipolar && (
        <>
          <div style={{ marginBottom: 12 }}>
            <BipolarRowTableEditor
              items={q.rows}
              questionId={q.id}
              onChange={(items) =>
                updateQuestion(index, {
                  rows: ensureBipolarRowArray(items, q.id),
                })
              }
            />
          </div>

          <div
            style={{
              display: "grid",
              gridTemplateColumns: "120px 120px",
              gap: 12,
              alignItems: "end",
            }}
          >
            <FieldBlock label="Min">
              <NumberInput
                value={q.min}
                min={1}
                max={100}
                onChange={(v) =>
                  updateQuestion(index, {
                    min: clampInt(v, 1, 100, q.min ?? 1),
                  })
                }
              />
            </FieldBlock>

            <FieldBlock label="Max">
              <NumberInput
                value={q.max}
                min={2}
                max={100}
                onChange={(v) =>
                  updateQuestion(index, {
                    max: clampInt(v, 2, 100, q.max ?? 7),
                  })
                }
              />
            </FieldBlock>
          </div>
        </>
      )}

      {isSlider && (
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "120px 120px 1fr 1fr",
            gap: 12,
            alignItems: "end",
          }}
        >
          <FieldBlock label="Min">
            <NumberInput
              value={q.min}
              min={0}
              max={100}
              onChange={(v) =>
                updateQuestion(index, {
                  min: clampInt(v, 0, 100, q.min ?? 1),
                })
              }
            />
          </FieldBlock>

          <FieldBlock label="Max">
            <NumberInput
              value={q.max}
              min={1}
              max={100}
              onChange={(v) =>
                updateQuestion(index, {
                  max: clampInt(v, 1, 100, q.max ?? 7),
                })
              }
            />
          </FieldBlock>

          <FieldBlock label="Left label">
            <TextInput
              value={q.left_label ?? ""}
              onChange={(v) => updateQuestion(index, { left_label: v })}
              placeholder="e.g. Low"
            />
          </FieldBlock>

          <FieldBlock label="Right label">
            <TextInput
              value={q.right_label ?? ""}
              onChange={(v) => updateQuestion(index, { right_label: v })}
              placeholder="e.g. High"
            />
          </FieldBlock>
        </div>
      )}
    </div>
  );
}

function smallActionButtonStyle(disabled) {
  return {
    width: INPUT_HEIGHT,
    height: INPUT_HEIGHT,
    borderRadius: 8,
    border: "1px solid #d1d5db",
    background: "#fff",
    color: disabled ? "#9ca3af" : "#111827",
    cursor: disabled ? "not-allowed" : "pointer",
    padding: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flex: "0 0 auto",
  };
}

function surveyListButtonStyle(isActive) {
  return {
    width: "100%",
    textAlign: "left",
    padding: "12px 14px",
    cursor: "pointer",
    borderRadius: 12,
    marginBottom: 8,
    background: isActive ? "#eef2ff" : "#fff",
    border: isActive ? "1px solid #c7d2fe" : "1px solid #e5e7eb",
    boxShadow: isActive ? "0 1px 2px rgba(79,70,229,0.10)" : "0 1px 2px rgba(0,0,0,0.03)",
    transition: "all 0.15s ease",
  };
}

/* =========================
   Main Component
   ========================= */

export function AdminSurveysPanel({ projectId: propProjectId, feedId, feeds: propFeeds }) {
  const projectId = propProjectId || getProjectId();

  const importFileRef = useRef(null);
  const [surveys, setSurveys] = useState([]);
  const [feeds, setFeeds] = useState(Array.isArray(propFeeds) ? propFeeds : []);
  const [selectedSurveyId, setSelectedSurveyId] = useState(null);
  const [survey, setSurvey] = useState(null);
  const [loading, setLoading] = useState(false);
  const [savingSurvey, setSavingSurvey] = useState(false);
  const [savingLinks, setSavingLinks] = useState(false);

  const [draggingQuestionId, setDraggingQuestionId] = useState(null);
  const [dragOverQuestionId, setDragOverQuestionId] = useState(null);

  useEffect(() => {
    if (Array.isArray(propFeeds)) {
      setFeeds(propFeeds);
    }
  }, [propFeeds]);

  async function loadAll() {
    setLoading(true);
    try {
      const incomingFeeds = Array.isArray(propFeeds) ? propFeeds : [];

      const [surveyList, feedList] = await Promise.all([
        listSurveysFromBackend({ projectId, force: true }),
        incomingFeeds.length
          ? Promise.resolve(incomingFeeds)
          : listFeedsFromBackend({ projectId }),
      ]);

      const safeSurveyList = Array.isArray(surveyList) ? surveyList : [];
      const safeFeedList = Array.isArray(feedList) ? feedList : [];

      const enrichedSurveyList = await Promise.all(
        safeSurveyList.map(async (s) => {
          if (!s?.survey_id) return s;

          try {
            const [full, linkedFeedIds] = await Promise.all([
              loadSurveyFromBackend(s.survey_id, {
                projectId,
                force: true,
              }),
              getLinkedFeedIdsForSurveyFromBackend({
                surveyId: s.survey_id,
                projectId,
                allFeeds: safeFeedList,
              }),
            ]);

            const normalizedFull = normalizeSurvey(full || {});
            return {
              ...s,
              ...normalizedFull,
              linked_feed_ids: normalizeLinkedFeedIds(linkedFeedIds),
              linked_project_id: projectId,
              trigger: normalizedFull.trigger || "after_feed_submit",
            };
          } catch {
            return {
              ...s,
              linked_feed_ids: [],
              linked_project_id: projectId,
              trigger: "after_feed_submit",
            };
          }
        })
      );

      setSurveys(enrichedSurveyList);
      setFeeds(safeFeedList);
    } catch (e) {
      console.warn("Failed to load surveys:", e);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadAll();
  }, [projectId]); // eslint-disable-line react-hooks/exhaustive-deps

  async function handleSelectSurvey(id) {
    setSelectedSurveyId(id);
    if (!id) {
      setSurvey(null);
      return;
    }

    try {
      const [s, linkedFeedIds] = await Promise.all([
        loadSurveyFromBackend(id, { projectId, force: true }),
        getLinkedFeedIdsForSurveyFromBackend({
          surveyId: id,
          projectId,
          allFeeds: feeds,
        }),
      ]);

      const normalized = normalizeSurvey(s || {});
      const editorSurvey = buildSurveyPagesFromFlatQuestions(
        {
          ...normalized,
          linked_feed_ids: normalizeLinkedFeedIds(linkedFeedIds),
          linked_project_id: projectId,
          trigger: normalized.trigger || "after_feed_submit",
        },
        flattenSurveyPagesForEditor(normalized)
      );

      setSurvey(editorSurvey);
    } catch (e) {
      console.warn("Failed to load survey:", e);
      setSurvey(null);
    }
  }

  function handleCreateSurvey() {
    const s = makeEmptySurvey({
      linked_project_id: projectId,
      linked_feed_ids: [],
      trigger: "after_feed_submit",
    });

    const editorSurvey = buildSurveyPagesFromFlatQuestions(
      {
        ...s,
        trigger: s.trigger || "after_feed_submit",
      },
      flattenSurveyPagesForEditor(s)
    );

    setSurvey(editorSurvey);
    setSelectedSurveyId(null);
  }

  function handleCopySurvey() {
  if (!survey) return;

  const copiedSurvey = resetSurveyIdentityForCopy(survey, {
    projectId,
    keepFeedLinks: true,
  });

  setSurvey(copiedSurvey);
  setSelectedSurveyId(null);
}

function handleExportSurvey() {
  if (!survey) return;

  const normalized = normalizeSurvey(survey);

  const exportPayload = {
    ...frontendSurveyToBackend(normalized),
    linked_feed_ids: normalizeLinkedFeedIds(normalized.linked_feed_ids),
    linked_project_id: normalized.linked_project_id || "",
    trigger: normalized.trigger || "after_feed_submit",
    exported_at: new Date().toISOString(),
    export_format: "survey_v1",
  };

  const blob = new Blob([JSON.stringify(exportPayload, null, 2)], {
    type: "application/json",
  });

  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  const safeName = slugifySurveyName(normalized.name || "survey")
    .replace(/[^\w\s-]/g, "")
    .replace(/\s+/g, "_");

  a.href = url;
  a.download = `${safeName || "survey"}.json`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

async function handleImportSurveyFile(event) {
  const file = event.target.files?.[0];
  if (!file) return;

  try {
    const text = await file.text();
    const parsed = JSON.parse(text);

    const normalizedImported = normalizeSurvey(parsed || {});
    const importedSurvey = resetSurveyIdentityForImport(normalizedImported, {
      projectId,
    });

    setSurvey(importedSurvey);
    setSelectedSurveyId(null);
  } catch (e) {
    console.warn("Failed to import survey:", e);
    alert("Failed to import survey JSON.");
  } finally {
    if (event.target) {
      event.target.value = "";
    }
  }
}

  async function handleSaveSurvey() {
    if (!survey) return;

    setSavingSurvey(true);
    try {
      const normalized = {
        ...survey,
        linked_project_id: projectId,
        linked_feed_ids: normalizeLinkedFeedIds(survey.linked_feed_ids),
        trigger: survey.trigger || "after_feed_submit",
      };

      const flatQuestions = getQuestionList(normalized);
      const rebuiltSurvey = buildSurveyPagesFromFlatQuestions(normalized, flatQuestions);

      const payload = {
        ...normalized,
        pages: (rebuiltSurvey.pages || []).map((page) => ({
          ...(page || { id: "page_1", title: "", description: "" }),
          questions: (page.questions || []).map((q, i) => buildSavedQuestion(q, i)),
        })),
      };

      const res = await saveSurveyToBackend(payload, { projectId });

      if (res?.ok) {
        const savedSurveyId = res.survey_id || payload.survey_id;

        const [fresh, linkedFeedIds] = await Promise.all([
          loadSurveyFromBackend(savedSurveyId, {
            projectId,
            force: true,
          }),
          getLinkedFeedIdsForSurveyFromBackend({
            surveyId: savedSurveyId,
            projectId,
            allFeeds: feeds,
          }),
        ]);

        const normalizedFresh = normalizeSurvey({
          ...(fresh || {}),
          linked_feed_ids: normalizeLinkedFeedIds(linkedFeedIds),
          linked_project_id: projectId,
          trigger: fresh?.trigger || normalized.trigger || "after_feed_submit",
        });

        const editorFresh = buildSurveyPagesFromFlatQuestions(
          normalizedFresh,
          flattenSurveyPagesForEditor(normalizedFresh)
        );

        setSelectedSurveyId(savedSurveyId);
        setSurvey(editorFresh);

        await loadAll();
        alert("Survey saved");
      } else {
        alert(res?.err || "Failed to save survey");
      }
    } catch (e) {
      console.warn("Failed to save survey:", e);
      alert("Failed to save survey");
    } finally {
      setSavingSurvey(false);
    }
  }

  async function handleDeleteSurvey() {
    if (!survey?.survey_id) return;
    if (!window.confirm("Delete this survey?")) return;

    try {
      const res = await deleteSurveyOnBackend(survey.survey_id, { projectId });
      if (res?.ok) {
        setSurvey(null);
        setSelectedSurveyId(null);
        await loadAll();
      } else {
        alert(res?.err || "Failed to delete survey");
      }
    } catch (e) {
      console.warn("Failed to delete survey:", e);
      alert("Failed to delete survey");
    }
  }

  function addQuestion(type) {
    setSurvey((prev) => {
      const currentQuestions = getQuestionList(prev);
      return setQuestionList(prev, [
        ...currentQuestions,
        makeBackendQuestionFromType(type, currentQuestions.length),
      ]);
    });
  }

  function insertQuestionAt(index, type, position = "below") {
    setSurvey((prev) => {
      const currentQuestions = getQuestionList(prev);
      const insertIndex = position === "above" ? index : index + 1;
      const nextQuestions = [...currentQuestions];
      nextQuestions.splice(insertIndex, 0, makeBackendQuestionFromType(type, insertIndex));
      return setQuestionList(prev, nextQuestions);
    });
  }

  function duplicateQuestion(index) {
    setSurvey((prev) => {
      const currentQuestions = [...getQuestionList(prev)];
      const sourceQuestion = currentQuestions[index];

      if (!sourceQuestion) return prev;

      const existingIds = currentQuestions
        .filter((q) => q?.type !== EDITOR_PAGE_BREAK_TYPE)
        .map((q) => q?.id)
        .filter(Boolean);

      const nextId = makeCopiedQuestionId(existingIds, sourceQuestion.id);

      let copiedQuestion = {
        ...sourceQuestion,
        _editorId: makeEditorId(),
        id: nextId,
        meta: sourceQuestion?.meta ? { ...sourceQuestion.meta } : {},
        visible_if: sourceQuestion?.visible_if
          ? JSON.parse(JSON.stringify(sourceQuestion.visible_if))
          : null,
      };

      if (shouldAutoRewriteRowValues(copiedQuestion)) {
        copiedQuestion = rewriteQuestionRowValues(copiedQuestion, nextId);
      }

      copiedQuestion = normalizeQuestionForEditor(copiedQuestion, index + 1);

      currentQuestions.splice(index + 1, 0, copiedQuestion);
      return setQuestionList(prev, currentQuestions);
    });
  }

  function updateQuestion(index, patch) {
    setSurvey((prev) => {
      const currentQuestions = [...getQuestionList(prev)];
      const currentQuestion = currentQuestions[index] || {};
      const merged =
        patch && typeof patch === "object" && !Array.isArray(patch)
          ? { ...currentQuestion, ...patch }
          : currentQuestion;

      currentQuestions[index] = normalizeQuestionForEditor(merged, index);
      return setQuestionList(prev, currentQuestions);
    });
  }

  function removeQuestion(index) {
    setSurvey((prev) => {
      const currentQuestions = [...getQuestionList(prev)];
      currentQuestions.splice(index, 1);
      return setQuestionList(prev, currentQuestions);
    });
  }

  function moveQuestion(fromIndex, toIndex) {
    setSurvey((prev) => {
      const currentQuestions = getQuestionList(prev);
      const reordered = reorderArray(currentQuestions, fromIndex, toIndex);
      return setQuestionList(prev, reordered);
    });
  }

  function handleQuestionDragStart(e, questionId) {
    setDraggingQuestionId(questionId);
    setDragOverQuestionId(questionId);
    try {
      e.dataTransfer.effectAllowed = "move";
      e.dataTransfer.setData("text/plain", String(questionId));
    } catch {}
  }

  function handleQuestionDragOver(e, questionId) {
    e.preventDefault();
    try {
      e.dataTransfer.dropEffect = "move";
    } catch {}
    if (dragOverQuestionId !== questionId) {
      setDragOverQuestionId(questionId);
    }
  }

  function handleQuestionDrop(e, targetQuestionId) {
    e.preventDefault();

    if (!survey || !draggingQuestionId || draggingQuestionId === targetQuestionId) {
      setDraggingQuestionId(null);
      setDragOverQuestionId(null);
      return;
    }

    const questions = getQuestionList(survey);
    const fromIndex = questions.findIndex((q) => q._editorId === draggingQuestionId);
    const toIndex = questions.findIndex((q) => q._editorId === targetQuestionId);

    if (fromIndex >= 0 && toIndex >= 0 && fromIndex !== toIndex) {
      moveQuestion(fromIndex, toIndex);
    }

    setDraggingQuestionId(null);
    setDragOverQuestionId(null);
  }

  function handleQuestionDragEnd() {
    setDraggingQuestionId(null);
    setDragOverQuestionId(null);
  }

  function toggleFeed(nextFeedId) {
    setSurvey((prev) => {
      const set = new Set(normalizeLinkedFeedIds(prev?.linked_feed_ids));
      if (set.has(nextFeedId)) set.delete(nextFeedId);
      else set.add(nextFeedId);

      return {
        ...prev,
        linked_feed_ids: Array.from(set),
      };
    });
  }

  async function handleSaveFeedLinks() {
    if (!survey?.survey_id) {
      alert("Save survey first before linking feeds.");
      return;
    }

    setSavingLinks(true);
    try {
      const res = await linkSurveyToFeedsOnBackend({
        surveyId: survey.survey_id,
        feedIds: normalizeLinkedFeedIds(survey.linked_feed_ids),
        projectId,
        allFeeds: feeds,
        trigger: survey.trigger || "after_feed_submit",
      });

      if (res?.ok) {
        const linkedIds = await getLinkedFeedIdsForSurveyFromBackend({
          surveyId: survey.survey_id,
          projectId,
          allFeeds: feeds,
        });

        setSurvey((prev) => ({
          ...prev,
          linked_feed_ids: normalizeLinkedFeedIds(linkedIds),
        }));

        await loadAll();
        alert("Feeds linked");
      } else {
        alert(res?.err || "Failed to link feeds");
      }
    } catch (e) {
      console.warn("Failed to link feeds:", e);
      alert("Failed to link feeds");
    } finally {
      setSavingLinks(false);
    }
  }

  const linkedFeedCount = useMemo(
    () => normalizeLinkedFeedIds(survey?.linked_feed_ids).length,
    [survey]
  );

  const currentQuestions = useMemo(() => getQuestionList(survey), [survey]);

  const questionDisplayNumbers = useMemo(() => {
    let count = 0;
    return currentQuestions.map((item) => {
      if (isCountedQuestionType(item?.type)) {
        count += 1;
        return count;
      }
      return null;
    });
  }, [currentQuestions]);

  const pageCount = useMemo(() => {
    if (!survey) return 0;
    const pages = buildSurveyPagesFromFlatQuestions(survey, currentQuestions).pages || [];
    return pages.length;
  }, [survey, currentQuestions]);

  return (
    <div style={{ display: "flex", gap: 24, alignItems: "flex-start" }}>
      <div
        style={{
          width: 280,
          flex: "0 0 280px",
          borderRight: "1px solid #e5e7eb",
          paddingRight: 18,
        }}
      >
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: 18,
          }}
        >
          <h3 style={{ margin: 0 }}>Survey list</h3>
          {loading && <span style={{ fontSize: 12, color: "#6b7280" }}>Loading…</span>}
        </div>

        <button
          type="button"
          onClick={handleCreateSurvey}
          style={{
            marginBottom: 14,
            width: "100%",
            padding: "12px 14px",
            borderRadius: 12,
            border: "1px solid #4f46e5",
            background: "#4f46e5",
            color: "#fff",
            fontWeight: 700,
            cursor: "pointer",
            boxShadow: "0 4px 10px rgba(79,70,229,0.18)",
          }}
        >
          + New Survey
        </button>

        <div>
          {surveys.map((s) => {
            const isActive = selectedSurveyId === s.survey_id;
            return (
              <button
                key={s.survey_id}
                type="button"
                onClick={() => handleSelectSurvey(s.survey_id)}
                style={surveyListButtonStyle(isActive)}
              >
                <div
                  style={{
                    fontWeight: 700,
                    color: isActive ? "#3730a3" : "#111827",
                    marginBottom: 4,
                  }}
                >
                  {s.name || s.survey_id}
                </div>
                <div style={{ fontSize: 12, color: "#6b7280" }}>
                  {surveyQuestionCount(s || {})} questions
                </div>
              </button>
            );
          })}
        </div>
      </div>

      <div style={{ flex: 1, minWidth: 0 }}>
        {!survey && <div style={{ color: "#6b7280" }}>Select or create a survey.</div>}

        {survey && (
  <>
    <div
      style={{
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 18,
      }}
    >
      <h3 style={{ margin: 0 }}>Survey Editor</h3>

      <div style={{ display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" }}>
        <div style={{ fontSize: 12, color: "#6b7280" }}>
          {linkedFeedCount} linked feed{linkedFeedCount === 1 ? "" : "s"} · {pageCount} page
          {pageCount === 1 ? "" : "s"}
        </div>

        <input
          ref={importFileRef}
          type="file"
          accept="application/json,.json"
          onChange={handleImportSurveyFile}
          style={{ display: "none" }}
        />

        <button
          type="button"
          onClick={() => importFileRef.current?.click()}
          style={{
            padding: "10px 14px",
            borderRadius: 10,
            border: "1px solid #d1d5db",
            background: "#fff",
            cursor: "pointer",
            fontWeight: 600,
          }}
        >
          Import
        </button>

        {survey && (
          <>
            <button
              type="button"
              onClick={handleCopySurvey}
              style={{
                padding: "10px 14px",
                borderRadius: 10,
                border: "1px solid #d1d5db",
                background: "#fff",
                cursor: "pointer",
                fontWeight: 600,
              }}
            >
              Copy
            </button>

            <button
              type="button"
              onClick={handleExportSurvey}
              style={{
                padding: "10px 14px",
                borderRadius: 10,
                border: "1px solid #d1d5db",
                background: "#fff",
                cursor: "pointer",
                fontWeight: 600,
              }}
            >
              Export
            </button>
          </>
        )}

        {!!survey?.survey_id && (
          <IconOnlyButton
            onClick={handleDeleteSurvey}
            title="Delete survey"
            danger
            size={17}
          />
        )}
      </div>
    </div>

            <SectionCard title="Survey details">
              <FieldBlock label="Survey name">
                <TextInput
                  value={survey.name}
                  onChange={(v) => setSurvey({ ...survey, name: v })}
                  placeholder="Survey name"
                />
              </FieldBlock>

              <FieldBlock label="Description">
                <TextAreaInput
                  value={survey.description}
                  onChange={(v) => setSurvey({ ...survey, description: v })}
                  placeholder="Description"
                  rows={3}
                />
              </FieldBlock>
            </SectionCard>

            <SectionCard
              title="Link to feeds"
              right={
                <button
                  type="button"
                  onClick={handleSaveFeedLinks}
                  disabled={savingLinks}
                  style={{
                    padding: "10px 14px",
                    borderRadius: 10,
                    border: "1px solid #d1d5db",
                    background: "#fff",
                    cursor: savingLinks ? "not-allowed" : "pointer",
                    fontWeight: 600,
                  }}
                >
                  {savingLinks ? "Saving..." : "Save Feed Links"}
                </button>
              }
            >
              <div
                style={{
                  border: "1px solid #d1d5db",
                  borderRadius: 10,
                  padding: 12,
                  maxHeight: 220,
                  overflow: "auto",
                }}
              >
                {feeds.length === 0 && <div style={{ color: "#6b7280" }}>No feeds found.</div>}

                {feeds.map((f) => (
                  <div key={f.feed_id} style={{ marginBottom: 8 }}>
                    <label
                      style={{
                        display: "flex",
                        alignItems: "center",
                        gap: 8,
                        cursor: "pointer",
                      }}
                    >
                      <input
                        type="checkbox"
                        checked={normalizeLinkedFeedIds(survey.linked_feed_ids).includes(f.feed_id)}
                        onChange={() => toggleFeed(f.feed_id)}
                      />
                      <span>{f.name || f.feed_id}</span>
                      {feedId && f.feed_id === feedId && (
                        <span style={{ fontSize: 12, color: "#6b7280" }}>(current)</span>
                      )}
                    </label>
                  </div>
                ))}
              </div>
            </SectionCard>

            <SectionCard title="Questions">
              <div style={{ fontSize: 12, color: "#6b7280", marginBottom: 18 }}>
                Drag items by the dotted handle to reorder them. Use the + buttons on the borders
                to insert new questions.
              </div>

              {currentQuestions.map((q, i) => (
                <QuestionCard
                  key={q._editorId || i}
                  q={q}
                  index={i}
                  displayNumber={questionDisplayNumbers[i]}
                  totalQuestions={currentQuestions.length}
                  updateQuestion={updateQuestion}
                  removeQuestion={removeQuestion}
                  moveQuestion={moveQuestion}
                  duplicateQuestion={duplicateQuestion}
                  insertQuestionAt={insertQuestionAt}
                  draggingId={draggingQuestionId}
                  dragOverId={dragOverQuestionId}
                  onDragStart={handleQuestionDragStart}
                  onDragOver={handleQuestionDragOver}
                  onDrop={handleQuestionDrop}
                  onDragEnd={handleQuestionDragEnd}
                />
              ))}

              {currentQuestions.length === 0 && (
                <div
                  style={{
                    position: "relative",
                    border: "1px dashed #d1d5db",
                    borderRadius: 12,
                    padding: 28,
                    background: "#fff",
                    textAlign: "center",
                    color: "#6b7280",
                  }}
                >
                  No questions yet.
                  <div style={{ marginTop: 10 }}>
                    <InsertAtBorderButton
                      position="bottom"
                      onInsert={(nextType) => addQuestion(nextType)}
                    />
                  </div>
                </div>
              )}
            </SectionCard>

            <div style={{ display: "flex", gap: 10 }}>
              <button
                type="button"
                onClick={handleSaveSurvey}
                disabled={savingSurvey}
                style={{
                  padding: "12px 16px",
                  borderRadius: 12,
                  border: "1px solid #4f46e5",
                  background: "#4f46e5",
                  color: "#fff",
                  fontWeight: 700,
                  cursor: savingSurvey ? "not-allowed" : "pointer",
                  boxShadow: "0 4px 10px rgba(79,70,229,0.18)",
                }}
              >
                {savingSurvey ? "Saving Survey..." : "Save Survey"}
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}