import React, { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";
import {
  makeEmptySurvey,
  makeQuestionByType,
  SURVEY_QUESTION_TYPES,
} from "../utils";

/* =========================
   Small helpers
   ========================== */

export const EDITOR_PAGE_BREAK_TYPE = "page_break";
const POST_REMINDER_TYPE =
  SURVEY_QUESTION_TYPES.POST_REMINDER || "post_reminder";

export const QUESTION_TYPE_LABELS = {
  [SURVEY_QUESTION_TYPES.TEXT]: "Text",
  [SURVEY_QUESTION_TYPES.TEXTAREA]: "Long text",
  [SURVEY_QUESTION_TYPES.SINGLE]: "Single choice",
  [SURVEY_QUESTION_TYPES.MULTI]: "Multiple choice",
  [SURVEY_QUESTION_TYPES.DROPDOWN]: "Dropdown",
  [SURVEY_QUESTION_TYPES.MATRIX_SINGLE]: "Matrix (single)",
  [SURVEY_QUESTION_TYPES.MATRIX_MULTI]: "Matrix (multi)",
  [SURVEY_QUESTION_TYPES.BIPOLAR]: "Bipolar scale",
  [SURVEY_QUESTION_TYPES.SLIDER]: "Slider",
  [SURVEY_QUESTION_TYPES.INFO]: "Info text",
  [POST_REMINDER_TYPE]: "Post reminder",
  [EDITOR_PAGE_BREAK_TYPE]: "Page break",
};

export const INSERTABLE_TYPES = [
  SURVEY_QUESTION_TYPES.TEXT,
  SURVEY_QUESTION_TYPES.TEXTAREA,
  SURVEY_QUESTION_TYPES.SINGLE,
  SURVEY_QUESTION_TYPES.MULTI,
  SURVEY_QUESTION_TYPES.DROPDOWN,
  SURVEY_QUESTION_TYPES.MATRIX_SINGLE,
  SURVEY_QUESTION_TYPES.MATRIX_MULTI,
  SURVEY_QUESTION_TYPES.BIPOLAR,
  SURVEY_QUESTION_TYPES.SLIDER,
  SURVEY_QUESTION_TYPES.INFO,
  POST_REMINDER_TYPE,
  EDITOR_PAGE_BREAK_TYPE,
];

const INPUT_HEIGHT = 42;
const TOP_ROW_LABEL_HEIGHT = 18;

export function makeEditorId() {
  return `editor_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`;
}

function clampInt(value, min, max, fallback) {
  const n = Number(value);
  if (!Number.isFinite(n)) return fallback;
  return Math.max(min, Math.min(max, Math.round(n)));
}

export function makeSequentialValue(prefix, index) {
  return `${prefix}_${index + 1}`;
}

export function makeNumericValue(index) {
  return String(index + 1);
}

export function sanitizeQuestionId(value, fallback = "") {
  const cleaned = String(value ?? "")
    .trim()
    .toUpperCase()
    .replace(/\s+/g, "_")
    .replace(/[^A-Z0-9_]/g, "");
  return cleaned || fallback;
}

export function sanitizeFreeformValue(value, fallback = "") {
  const cleaned = String(value ?? "")
    .trim()
    .replace(/\s+/g, "_")
    .replace(/[^\w-]/g, "");
  return cleaned || fallback;
}

export function preserveEmptyOrSanitize(value, fallback = "") {
  if (value === "") return "";
  if (value === null || value === undefined) return fallback;
  return sanitizeFreeformValue(value, fallback);
}

function uniqueStringList(values = []) {
  return Array.from(
    new Set(
      (Array.isArray(values) ? values : [])
        .map((x) => String(x ?? "").trim())
        .filter(Boolean)
    )
  );
}

export function normalizeVisibleInFeeds(values = []) {
  return uniqueStringList(values);
}

function normalizeRichTextHtml(value) {
  const raw = String(value ?? "").trim();
  if (!raw) return "";

  const looksLikeHtml = /<\/?[a-z][\s\S]*>/i.test(raw);
  if (looksLikeHtml) return raw;

  const escaped = raw
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  return escaped
    .split(/\n{2,}/)
    .map((block) => `<p>${block.replace(/\n/g, "<br>")}</p>`)
    .join("");
}

function stripHtmlForEmptyCheck(html = "") {
  return String(html || "")
    .replace(/<br\s*\/?>/gi, "")
    .replace(/<\/p>\s*<p>/gi, "")
    .replace(/<[^>]*>/g, "")
    .replace(/&nbsp;/gi, " ")
    .trim();
}

export function normalizeFeedOverridesMap(value = {}) {
  const input =
    value && typeof value === "object" && !Array.isArray(value) ? value : {};
  const out = {};

  Object.entries(input).forEach(([feedId, override]) => {
    const cleanFeedId = String(feedId || "").trim();
    if (!cleanFeedId) return;

    const safeOverride =
      override && typeof override === "object" && !Array.isArray(override)
        ? override
        : {};

    out[cleanFeedId] = {
      text: normalizeRichTextHtml(safeOverride.text ?? ""),
    };
  });

  return out;
}

export function pruneFeedOverridesMap(value = {}, allowedFeedIds = []) {
  const allowed = new Set(uniqueStringList(allowedFeedIds));
  const normalized = normalizeFeedOverridesMap(value);
  const out = {};

  Object.entries(normalized).forEach(([feedId, override]) => {
    if (allowed.size && !allowed.has(feedId)) return;
    if (stripHtmlForEmptyCheck(override?.text ?? "")) {
      out[feedId] = {
        text: normalizeRichTextHtml(override.text ?? ""),
      };
    }
  });

  return out;
}

export function isQuestionIdAutoGenerated(value = "") {
  return /^(Q_\d+|Q_\d+_\d+|Q_\d{6,}|Q_[A-Z0-9]+|q_\d+|q_[A-Za-z0-9_-]+)$/.test(
    String(value || "").trim()
  );
}

export function makeMatrixRowValue(questionId, index) {
  const base = sanitizeQuestionId(questionId);
  return base ? `${base}_${index + 1}` : makeSequentialValue("row", index);
}

export function shouldAutoRewriteRowValues(question) {
  const type = question?.type;
  return (
    type === SURVEY_QUESTION_TYPES.MATRIX_SINGLE ||
    type === SURVEY_QUESTION_TYPES.MATRIX_MULTI ||
    type === SURVEY_QUESTION_TYPES.BIPOLAR
  );
}

function isEditorDisplayOnlyType(type) {
  return type === SURVEY_QUESTION_TYPES.INFO || type === POST_REMINDER_TYPE;
}

export function ensureChoiceArray(items = []) {
  return (Array.isArray(items) ? items : []).map((item, i) => ({
    value: preserveEmptyOrSanitize(item?.value, makeNumericValue(i)),
    label: String(item?.label ?? ""),
  }));
}

export function ensureMatrixArray(items = [], prefix = "item") {
  const useNumericDefault = prefix === "col";

  return (Array.isArray(items) ? items : []).map((item, i) => ({
    value: preserveEmptyOrSanitize(
      item?.value,
      useNumericDefault ? makeNumericValue(i) : makeSequentialValue(prefix, i)
    ),
    label: String(item?.label ?? ""),
  }));
}

export function ensureMatrixRowsFromQuestionId(items = [], questionId = "") {
  return (Array.isArray(items) ? items : []).map((item, i) => ({
    value: preserveEmptyOrSanitize(item?.value, makeMatrixRowValue(questionId, i)),
    label: String(item?.label ?? ""),
  }));
}

export function ensureBipolarRowArray(items = [], questionId = "") {
  return (Array.isArray(items) ? items : []).map((item, i) => {
    const leftLabel = String(item?.left_label ?? item?.label ?? "");
    const rightLabel = String(item?.right_label ?? "");
    const label = String(item?.label ?? item?.left_label ?? `Row ${i + 1}`);

    return {
      value: preserveEmptyOrSanitize(item?.value, makeMatrixRowValue(questionId, i)),
      label,
      left_label: leftLabel,
      right_label: rightLabel,
    };
  });
}

export function rewriteQuestionRowValues(question, nextQuestionId) {
  if (!shouldAutoRewriteRowValues(question)) return question;

  const nextId = sanitizeQuestionId(nextQuestionId, question?.id || "");
  if (!nextId) return question;

  return {
    ...question,
    rows: (Array.isArray(question?.rows) ? question.rows : []).map((row, i) => ({
      ...row,
      value: makeMatrixRowValue(nextId, i),
    })),
  };
}

export function makeCopiedQuestionId(existingIds = [], sourceId = "") {
  const cleanSourceId = sanitizeQuestionId(sourceId, `Q_${Date.now()}`);
  const idSet = new Set(
    (Array.isArray(existingIds) ? existingIds : []).map((x) =>
      String(x || "").trim()
    )
  );

  let nextId = `${cleanSourceId}_COPY`;
  if (!idSet.has(nextId)) return nextId;

  let counter = 2;
  while (idSet.has(`${cleanSourceId}_COPY_${counter}`)) {
    counter += 1;
  }

  return `${cleanSourceId}_COPY_${counter}`;
}

export function reorderArray(list = [], fromIndex, toIndex) {
  const arr = [...list];
  if (
    fromIndex === toIndex ||
    fromIndex < 0 ||
    toIndex < 0 ||
    fromIndex >= arr.length ||
    toIndex >= arr.length
  ) {
    return arr;
  }

  const [moved] = arr.splice(fromIndex, 1);
  arr.splice(toIndex, 0, moved);
  return arr;
}

export function isCountedQuestionType(type) {
  return (
    type !== SURVEY_QUESTION_TYPES.INFO &&
    type !== POST_REMINDER_TYPE &&
    type !== EDITOR_PAGE_BREAK_TYPE
  );
}

function derivePostOptionLabel(post = {}, index = 0, feedName = "") {
  const explicitName = String(post?.name || "").trim();
  if (explicitName) return feedName ? `${feedName} · ${explicitName}` : explicitName;

  const author = String(post?.author || post?.username || "").trim();
  const text = String(post?.text || post?.caption || post?.body || "")
    .replace(/<[^>]*>/g, " ")
    .replace(/\s+/g, " ")
    .trim();

  let base = `Post ${index + 1}`;
  if (author && text) base = `${author}: ${text.slice(0, 80)}`;
  else if (author) base = author;
  else if (text) base = text.slice(0, 80);

  return feedName ? `${feedName} · ${base}` : base;
}

function getRelevantFeedIdsForQuestion(q, linkedFeeds = []) {
  const linkedFeedIds = (Array.isArray(linkedFeeds) ? linkedFeeds : [])
    .map((feed) => String(feed?.feed_id || "").trim())
    .filter(Boolean);

  const visibleFeedIds = normalizeVisibleInFeeds(q?.visible_in_feeds);

  if (visibleFeedIds.length === 0) return linkedFeedIds;

  const linkedSet = new Set(linkedFeedIds);
  return visibleFeedIds.filter((feedId) => linkedSet.has(feedId));
}

function getAvailablePostsForQuestion(q, linkedFeeds = [], linkedFeedPostsMap = {}) {
  if (q?.type !== POST_REMINDER_TYPE) return [];

  const relevantFeedIds = getRelevantFeedIdsForQuestion(q, linkedFeeds);
  const linkedFeedLookup = new Map(
    (Array.isArray(linkedFeeds) ? linkedFeeds : []).map((feed) => [
      String(feed?.feed_id || "").trim(),
      feed,
    ])
  );


  const seen = new Set();
  const out = [];

  relevantFeedIds.forEach((feedId) => {
    const posts = Array.isArray(linkedFeedPostsMap?.[feedId])
      ? linkedFeedPostsMap[feedId]
      : [];
    const feed = linkedFeedLookup.get(feedId);
    const feedName = String(feed?.name || feedId || "").trim();

    posts.forEach((post, postIndex) => {
      const postId = String(post?.id || "").trim();
      if (!postId) return;

      const dedupeKey = `${feedId}::${postId}`;
      if (seen.has(dedupeKey)) return;
      seen.add(dedupeKey);

      out.push({
        ...post,
        _feed_id: feedId,
        _feed_name: feedName,
        _option_label: derivePostOptionLabel(post, postIndex, feedName),
      });
    });
  });

  return out;
}

export function normalizeQuestionForEditor(q = {}, index = 0) {
  const type = q?.type || SURVEY_QUESTION_TYPES.TEXT;

  if (type === EDITOR_PAGE_BREAK_TYPE) {
    return {
      _editorId: q?._editorId || makeEditorId(),
      id: q?.id || `page_break_${index + 1}`,
      type: EDITOR_PAGE_BREAK_TYPE,
      text: "",
      required: false,
      choices: [],
      rows: [],
      columns: [],
      min: 1,
      max: 7,
      left_label: "",
      right_label: "",
      placeholder: "",
      visible_if: null,
      visible_in_feeds: [],
      feed_overrides: {},
      post_id: "",
      post_label: "",
      post_feed_id: "",
      _showFeedVisibilityEditor: false,
      _showFeedOverridesEditor: false,
      meta: q?.meta || {},
    };
  }

  const normalizedId = sanitizeQuestionId(q?.id, "");

  return {
    _editorId: q?._editorId || makeEditorId(),
    id: normalizedId,
    type,
    text: normalizeRichTextHtml(q?.text ?? ""),
    required: isEditorDisplayOnlyType(type) ? false : !!q?.required,
    choices: ensureChoiceArray(q?.choices),
    rows:
      type === SURVEY_QUESTION_TYPES.BIPOLAR
        ? ensureBipolarRowArray(q?.rows, normalizedId)
        : type === SURVEY_QUESTION_TYPES.MATRIX_SINGLE ||
            type === SURVEY_QUESTION_TYPES.MATRIX_MULTI
          ? ensureMatrixRowsFromQuestionId(q?.rows, normalizedId)
          : [],
    columns: ensureMatrixArray(q?.columns, "col"),
    min: Number.isFinite(q?.min) ? q.min : 1,
    max: Number.isFinite(q?.max) ? q.max : 7,
    left_label: String(q?.left_label ?? ""),
    right_label: String(q?.right_label ?? ""),
    placeholder: String(q?.placeholder ?? ""),
    visible_if: q?.visible_if || null,
    visible_in_feeds: normalizeVisibleInFeeds(q?.visible_in_feeds),
    feed_overrides: normalizeFeedOverridesMap(q?.feed_overrides),
    post_id: String(q?.post_id ?? ""),
    post_label: String(q?.post_label ?? ""),
    post_feed_id: String(q?.post_feed_id ?? q?.meta?.post_feed_id ?? ""),
    _showFeedVisibilityEditor: !!q?._showFeedVisibilityEditor,
    _showFeedOverridesEditor: !!q?._showFeedOverridesEditor,
    meta: q?.meta || {},
  };
}

export function flattenSurveyPagesForEditor(survey) {
  const sourceSurvey =
    survey && typeof survey === "object" ? survey : makeEmptySurvey();

  const pages = Array.isArray(sourceSurvey.pages) ? sourceSurvey.pages : [];
  const flat = [];

  if (pages.length === 0) return [];

  pages.forEach((page, pageIndex) => {
    const questions = Array.isArray(page?.questions) ? page.questions : [];

    questions.forEach((q) => {
      flat.push(normalizeQuestionForEditor(q, flat.length));
    });

    if (pageIndex < pages.length - 1) {
      flat.push(
        normalizeQuestionForEditor(
          {
            _editorId: `editor_page_break_${pageIndex + 1}`,
            id: `page_break_${pageIndex + 1}`,
            type: EDITOR_PAGE_BREAK_TYPE,
          },
          flat.length
        )
      );
    }
  });

  return flat;
}

export function buildSurveyPagesFromFlatQuestions(survey, items) {
  const safeSurvey =
    survey && typeof survey === "object" ? survey : makeEmptySurvey();

  const flatItems = Array.isArray(items) ? items : [];
  const existingPages = Array.isArray(safeSurvey.pages) ? safeSurvey.pages : [];
  const splitPages = [];
  let currentQuestions = [];

  flatItems.forEach((item) => {
    if (item?.type === EDITOR_PAGE_BREAK_TYPE) {
      splitPages.push(currentQuestions);
      currentQuestions = [];
    } else {
      currentQuestions.push(
        normalizeQuestionForEditor(item, currentQuestions.length)
      );
    }
  });

  splitPages.push(currentQuestions);

  const pages = splitPages.map((questions, pageIndex) => {
    const existingPage = existingPages[pageIndex] || {};
    return {
      id: existingPage.id || `page_${pageIndex + 1}`,
      title: String(existingPage.title ?? ""),
      description: String(existingPage.description ?? ""),
      questions: questions.map((q, i) => normalizeQuestionForEditor(q, i)),
    };
  });

  return {
    ...safeSurvey,
    pages: pages.length
      ? pages
      : [
          {
            id: "page_1",
            title: "",
            description: "",
            questions: [],
          },
        ],
  };
}

export function getQuestionList(survey) {
  return flattenSurveyPagesForEditor(survey);
}

export function setQuestionList(survey, questions) {
  return buildSurveyPagesFromFlatQuestions(survey, questions);
}

export function makePageBreakForEditor(index = 0) {
  return normalizeQuestionForEditor(
    {
      id: `page_break_${Date.now()}_${index}`,
      type: EDITOR_PAGE_BREAK_TYPE,
    },
    index
  );
}

export function makeBackendQuestionFromType(type, index = 0) {
  if (type === EDITOR_PAGE_BREAK_TYPE) {
    return makePageBreakForEditor(index);
  }

  const base = makeQuestionByType(type);
  const fallbackId = sanitizeQuestionId(base?.id, `Q_${Date.now()}`);

  const question = {
    id:
      base?.id && !isQuestionIdAutoGenerated(base.id)
        ? sanitizeQuestionId(base.id, fallbackId)
        : `Q_${Date.now()}`,
    type,
    text: normalizeRichTextHtml(String(base?.text ?? base?.label ?? "")),
    required: isEditorDisplayOnlyType(type) ? false : !!base?.required,
    choices: [],
    rows: [],
    columns: [],
    min: Number.isFinite(base?.min) ? base.min : 1,
    max: Number.isFinite(base?.max) ? base.max : 7,
    left_label: String(base?.left_label ?? base?.min_label ?? ""),
    right_label: String(base?.right_label ?? base?.max_label ?? ""),
    placeholder: String(base?.placeholder ?? ""),
    visible_if: base?.visible_if || null,
    visible_in_feeds: normalizeVisibleInFeeds(base?.visible_in_feeds),
    feed_overrides: normalizeFeedOverridesMap(base?.feed_overrides),
    post_id: String(base?.post_id ?? ""),
    post_label: String(base?.post_label ?? ""),
    post_feed_id: String(base?.post_feed_id ?? ""),
    _showFeedVisibilityEditor: false,
    _showFeedOverridesEditor: false,
    meta: base?.meta || {},
  };

  if (type === POST_REMINDER_TYPE) {
    question.text =
      normalizeRichTextHtml(
        String(
          base?.text ??
            "<p><b>Please look at this post again before answering.</b></p>"
        )
      ) ||
      "<p><b>Please look at this post again before answering.</b></p>";
    question.required = false;
  }

  if (
    type === SURVEY_QUESTION_TYPES.SINGLE ||
    type === SURVEY_QUESTION_TYPES.MULTI ||
    type === SURVEY_QUESTION_TYPES.DROPDOWN
  ) {
    const source =
      Array.isArray(base?.choices) && base.choices.length
        ? base.choices
        : Array.isArray(base?.options)
          ? base.options.map((label, i) => ({
              value: makeNumericValue(i),
              label: String(label || ""),
            }))
          : [];

    question.choices = ensureChoiceArray(source);
  }

  if (
    type === SURVEY_QUESTION_TYPES.MATRIX_SINGLE ||
    type === SURVEY_QUESTION_TYPES.MATRIX_MULTI
  ) {
    const srcRows = Array.isArray(base?.rows) && base.rows.length ? base.rows : [];
    const srcCols =
      Array.isArray(base?.columns) && base.columns.length ? base.columns : [];
    question.rows = ensureMatrixRowsFromQuestionId(srcRows, question.id);
    question.columns = ensureMatrixArray(srcCols, "col");
  }

  if (type === SURVEY_QUESTION_TYPES.BIPOLAR) {
    const srcRows = Array.isArray(base?.rows) && base.rows.length ? base.rows : [];
    question.rows = ensureBipolarRowArray(srcRows, question.id);
  }

  return normalizeQuestionForEditor(question, index);
}

export function buildSavedQuestion(q, index) {
  const cleanQ = normalizeQuestionForEditor(q, index);

  return {
    id: sanitizeQuestionId(cleanQ.id, `Q_${index + 1}`),
    type: cleanQ.type,
    text: cleanQ.text,
    description: "",
    required: isEditorDisplayOnlyType(cleanQ.type) ? false : !!cleanQ.required,
    choices:
      cleanQ.type === SURVEY_QUESTION_TYPES.SINGLE ||
      cleanQ.type === SURVEY_QUESTION_TYPES.MULTI ||
      cleanQ.type === SURVEY_QUESTION_TYPES.DROPDOWN
        ? ensureChoiceArray(cleanQ.choices)
        : [],
    rows:
      cleanQ.type === SURVEY_QUESTION_TYPES.BIPOLAR
        ? (Array.isArray(cleanQ.rows) ? cleanQ.rows : []).map((row, i) => ({
            value: preserveEmptyOrSanitize(
              row?.value,
              makeMatrixRowValue(cleanQ.id, i)
            ),
            label: String(
              row?.label ?? row?.left_label ?? `Row ${i + 1}`
            ).trim(),
            left_label: String(row?.left_label ?? row?.label ?? "").trim(),
            right_label: String(row?.right_label ?? "").trim(),
          }))
        : cleanQ.type === SURVEY_QUESTION_TYPES.MATRIX_SINGLE ||
            cleanQ.type === SURVEY_QUESTION_TYPES.MATRIX_MULTI
          ? ensureMatrixRowsFromQuestionId(cleanQ.rows, cleanQ.id)
          : [],
    columns:
      cleanQ.type === SURVEY_QUESTION_TYPES.MATRIX_SINGLE ||
      cleanQ.type === SURVEY_QUESTION_TYPES.MATRIX_MULTI
        ? ensureMatrixArray(cleanQ.columns, "col")
        : [],
    left_label: cleanQ.left_label || "",
    right_label: cleanQ.right_label || "",
    min: Number.isFinite(cleanQ.min) ? cleanQ.min : 1,
    max: Number.isFinite(cleanQ.max) ? cleanQ.max : 7,
    placeholder: cleanQ.placeholder || "",
    visible_if: cleanQ.visible_if || null,
    visible_in_feeds: normalizeVisibleInFeeds(cleanQ.visible_in_feeds),
    feed_overrides: pruneFeedOverridesMap(
      cleanQ.feed_overrides,
      normalizeVisibleInFeeds(cleanQ.visible_in_feeds)
    ),
    post_id: cleanQ.type === POST_REMINDER_TYPE ? String(cleanQ.post_id || "") : "",
    post_label:
      cleanQ.type === POST_REMINDER_TYPE ? String(cleanQ.post_label || "") : "",
    post_feed_id:
      cleanQ.type === POST_REMINDER_TYPE
        ? String(cleanQ.post_feed_id || "")
        : "",
    meta:
      cleanQ.type === POST_REMINDER_TYPE
        ? {
            ...(cleanQ.meta || {}),
            post_feed_id: String(cleanQ.post_feed_id || ""),
          }
        : cleanQ.meta || {},
    randomize_options: false,
  };
}

/* =========================
   Small icon/button helpers
   ========================= */

function TrashIcon({ size = 16 }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      aria-hidden="true"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="3 6 5 6 21 6" />
      <path d="M8 6V4a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v2" />
      <path d="M19 6l-1 14a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1L5 6" />
      <line x1="10" y1="11" x2="10" y2="17" />
      <line x1="14" y1="11" x2="14" y2="17" />
    </svg>
  );
}

function PlusIcon({ size = 15 }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      aria-hidden="true"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" y1="5" x2="12" y2="19" />
      <line x1="5" y1="12" x2="19" y2="12" />
    </svg>
  );
}

function CopyIcon({ size = 16 }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      aria-hidden="true"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  );
}

function BoldIcon({ size = 14 }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      aria-hidden="true"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 5h6a4 4 0 0 1 0 8H7z" />
      <path d="M7 13h7a4 4 0 0 1 0 8H7z" />
    </svg>
  );
}

function ItalicIcon({ size = 14 }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      aria-hidden="true"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="19" y1="4" x2="10" y2="4" />
      <line x1="14" y1="20" x2="5" y2="20" />
      <line x1="15" y1="4" x2="9" y2="20" />
    </svg>
  );
}

function ListIcon({ size = 14 }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      aria-hidden="true"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="8" y1="6" x2="21" y2="6" />
      <line x1="8" y1="12" x2="21" y2="12" />
      <line x1="8" y1="18" x2="21" y2="18" />
      <circle cx="4" cy="6" r="1" fill="currentColor" stroke="none" />
      <circle cx="4" cy="12" r="1" fill="currentColor" stroke="none" />
      <circle cx="4" cy="18" r="1" fill="currentColor" stroke="none" />
    </svg>
  );
}

function OrderedListIcon({ size = 14 }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      aria-hidden="true"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="10" y1="6" x2="21" y2="6" />
      <line x1="10" y1="12" x2="21" y2="12" />
      <line x1="10" y1="18" x2="21" y2="18" />
      <path d="M4 7V4l-1 1" />
      <path d="M3 10h1a1 1 0 0 1 0 2H3l2 2h-2" />
      <path d="M3 16h2a1 1 0 0 1 0 2H3m1-3v6" />
    </svg>
  );
}

function EyeIcon({ size = 14 }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      aria-hidden="true"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M1 12s4-7 11-7 11 7 11 7-4 7-11 7S1 12 1 12Z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  );
}

function TextCursorIcon({ size = 14 }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      aria-hidden="true"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 7V5h16v2" />
      <path d="M12 5v14" />
      <path d="M8 19h8" />
    </svg>
  );
}

function ChevronDownIcon({ size = 14, open = false }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      aria-hidden="true"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      style={{
        transform: open ? "rotate(180deg)" : "rotate(0deg)",
        transition: "transform 0.15s ease",
      }}
    >
      <polyline points="6 9 12 15 18 9" />
    </svg>
  );
}

function IconOnlyButton({
  onClick,
  title,
  danger = false,
  disabled = false,
  style = {},
  size = 16,
  children = null,
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      title={title}
      aria-label={title}
      disabled={disabled}
      style={{
        width: INPUT_HEIGHT,
        height: INPUT_HEIGHT,
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 8,
        border: `1px solid ${danger ? "#dc2626" : "#d1d5db"}`,
        background: "#fff",
        color: danger ? "#dc2626" : disabled ? "#9ca3af" : "#111827",
        cursor: disabled ? "not-allowed" : "pointer",
        padding: 0,
        lineHeight: 1,
        ...style,
      }}
    >
      {children || <TrashIcon size={size} />}
    </button>
  );
}

function SecondaryPillButton({
  onClick,
  active = false,
  children,
  title,
  disabled = false,
}) {
  return (
    <button
      type="button"
      title={title}
      onClick={onClick}
      disabled={disabled}
      style={{
        height: 34,
        padding: "0 12px",
        borderRadius: 999,
        border: `1px solid ${active ? "#c7d2fe" : "#d1d5db"}`,
        background: active ? "#eef2ff" : "#fff",
        color: active ? "#4338ca" : disabled ? "#9ca3af" : "#111827",
        fontSize: 12,
        fontWeight: 600,
        cursor: disabled ? "not-allowed" : "pointer",
        display: "inline-flex",
        alignItems: "center",
        gap: 6,
        whiteSpace: "nowrap",
      }}
    >
      {children}
    </button>
  );
}

function DragHandle({ onDragStart, onDragEnd }) {
  return (
    <div
      draggable
      onDragStart={onDragStart}
      onDragEnd={onDragEnd}
      title="Drag to reorder"
      style={{
        width: INPUT_HEIGHT,
        height: INPUT_HEIGHT,
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 8,
        border: "1px solid #d1d5db",
        background: "#fff",
        cursor: "grab",
        fontSize: 15,
        color: "#6b7280",
        userSelect: "none",
      }}
    >
      ⋮⋮
    </div>
  );
}

function RequiredToggleButton({ active, onClick, disabled = false }) {
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      title={active ? "Required" : "Optional"}
      style={{
        height: INPUT_HEIGHT,
        minWidth: 92,
        padding: "0 12px",
        borderRadius: 8,
        border: `1px solid ${active ? "#4f46e5" : "#d1d5db"}`,
        background: active ? "#eef2ff" : "#fff",
        color: active ? "#4338ca" : disabled ? "#9ca3af" : "#111827",
        fontWeight: 600,
        cursor: disabled ? "not-allowed" : "pointer",
        whiteSpace: "nowrap",
      }}
    >
      {active ? "Required" : "Optional"}
    </button>
  );
}

function TopField({ label, children }) {
  return (
    <div>
      <div
        style={{
          fontSize: 13,
          fontWeight: 600,
          marginBottom: 4,
          height: TOP_ROW_LABEL_HEIGHT,
          lineHeight: `${TOP_ROW_LABEL_HEIGHT}px`,
        }}
      >
        {label}
      </div>
      {children}
    </div>
  );
}

/* =========================
   Reusable editors
   ========================= */

function TextInput({ value, onChange, placeholder, style }) {
  return (
    <input
      value={value ?? ""}
      onChange={(e) => onChange(e.target.value)}
      placeholder={placeholder}
      style={{
        width: "100%",
        height: INPUT_HEIGHT,
        padding: "8px 10px",
        borderRadius: 8,
        border: "1px solid #d1d5db",
        boxSizing: "border-box",
        ...style,
      }}
    />
  );
}

function NumberInput({ value, onChange, min, max, step = 1, style }) {
  return (
    <input
      type="number"
      value={value ?? ""}
      min={min}
      max={max}
      step={step}
      onChange={(e) => onChange(e.target.value)}
      style={{
        width: "100%",
        height: INPUT_HEIGHT,
        padding: "8px 10px",
        borderRadius: 8,
        border: "1px solid #d1d5db",
        boxSizing: "border-box",
        ...style,
      }}
    />
  );
}

function TextAreaInput({ value, onChange, placeholder, rows = 3, style }) {
  return (
    <textarea
      value={value ?? ""}
      onChange={(e) => onChange(e.target.value)}
      placeholder={placeholder}
      rows={rows}
      style={{
        width: "100%",
        padding: "8px 10px",
        borderRadius: 8,
        border: "1px solid #d1d5db",
        resize: "vertical",
        boxSizing: "border-box",
        ...style,
      }}
    />
  );
}

function SelectInput({ value, onChange, children, style, disabled = false }) {
  return (
    <select
      value={value}
      onChange={(e) => onChange(e.target.value)}
      disabled={disabled}
      style={{
        width: "100%",
        height: INPUT_HEIGHT,
        padding: "8px 10px",
        borderRadius: 8,
        border: "1px solid #d1d5db",
        background: "#fff",
        boxSizing: "border-box",
        ...style,
      }}
    >
      {children}
    </select>
  );
}

function FieldBlock({ label, children, hint = "" }) {
  return (
    <div style={{ marginBottom: 10 }}>
      <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 4 }}>
        {label}
      </div>
      {children}
      {hint ? (
        <div style={{ fontSize: 12, color: "#6b7280", marginTop: 4 }}>
          {hint}
        </div>
      ) : null}
    </div>
  );
}

function SectionCard({ title, children, right = null }) {
  return (
    <div
      style={{
        border: "1px solid #e5e7eb",
        borderRadius: 14,
        background: "#fff",
        padding: 16,
        marginBottom: 18,
        boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
      }}
    >
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          gap: 12,
          marginBottom: 12,
        }}
      >
        <h4 style={{ margin: 0, fontSize: 16 }}>{title}</h4>
        {right}
      </div>
      {children}
    </div>
  );
}

function RichToolbarButton({ title, onMouseDown, active = false, children }) {
  return (
    <button
      type="button"
      title={title}
      aria-label={title}
      onMouseDown={onMouseDown}
      style={{
        width: 32,
        height: 32,
        borderRadius: 8,
        border: `1px solid ${active ? "#4f46e5" : "#d1d5db"}`,
        background: active ? "#eef2ff" : "#fff",
        color: active ? "#4338ca" : "#111827",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        cursor: "pointer",
        padding: 0,
      }}
    >
      {children}
    </button>
  );
}

function RichTextEditor({ value, onChange, placeholder = "Question text" }) {
  const editorRef = useRef(null);
  const [focused, setFocused] = useState(false);
  const [formats, setFormats] = useState({
    bold: false,
    italic: false,
    insertUnorderedList: false,
    insertOrderedList: false,
  });

  const normalizedValue = normalizeRichTextHtml(value);

  useEffect(() => {
    const el = editorRef.current;
    if (!el) return;

    if (el.innerHTML !== normalizedValue) {
      el.innerHTML = normalizedValue || "";
    }
  }, [normalizedValue]);

  function updateFormats() {
    try {
      setFormats({
        bold: !!document.queryCommandState("bold"),
        italic: !!document.queryCommandState("italic"),
        insertUnorderedList: !!document.queryCommandState("insertUnorderedList"),
        insertOrderedList: !!document.queryCommandState("insertOrderedList"),
      });
    } catch {
      setFormats({
        bold: false,
        italic: false,
        insertUnorderedList: false,
        insertOrderedList: false,
      });
    }
  }

  function emitChange() {
    const el = editorRef.current;
    if (!el) return;

    const rawHtml = el.innerHTML || "";
    const textOnly = stripHtmlForEmptyCheck(rawHtml);

    if (!textOnly) {
      onChange("");
      return;
    }

    onChange(rawHtml);
  }

  function runCommand(command, commandValue = null) {
    const el = editorRef.current;
    if (!el) return;

    el.focus();

    try {
      document.execCommand(command, false, commandValue);
    } catch {}

    if (command === "formatBlock") {
      try {
        document.execCommand("defaultParagraphSeparator", false, "p");
      } catch {}
    }

    updateFormats();
    emitChange();
  }

  function handleInput() {
    emitChange();
    updateFormats();
  }

  function handlePaste(e) {
    e.preventDefault();
    const text = e.clipboardData?.getData("text/plain") || "";
    try {
      document.execCommand("insertText", false, text);
    } catch {
      const el = editorRef.current;
      if (!el) return;
      el.innerText = `${el.innerText || ""}${text}`;
    }
    emitChange();
    updateFormats();
  }

  const isEmpty = !stripHtmlForEmptyCheck(normalizedValue);

  return (
    <div
      style={{
        border: `1px solid ${focused ? "#4f46e5" : "#d1d5db"}`,
        borderRadius: 10,
        overflow: "hidden",
        background: "#fff",
        boxShadow: focused ? "0 0 0 3px rgba(79,70,229,0.10)" : "none",
      }}
    >
      <div
        style={{
          display: "flex",
          gap: 6,
          alignItems: "center",
          padding: 8,
          borderBottom: "1px solid #e5e7eb",
          background: "#fafafa",
          flexWrap: "wrap",
        }}
      >
        <RichToolbarButton
          title="Bold"
          active={formats.bold}
          onMouseDown={(e) => {
            e.preventDefault();
            runCommand("bold");
          }}
        >
          <BoldIcon size={14} />
        </RichToolbarButton>

        <RichToolbarButton
          title="Italic"
          active={formats.italic}
          onMouseDown={(e) => {
            e.preventDefault();
            runCommand("italic");
          }}
        >
          <ItalicIcon size={14} />
        </RichToolbarButton>

        <RichToolbarButton
          title="Bullet list"
          active={formats.insertUnorderedList}
          onMouseDown={(e) => {
            e.preventDefault();
            runCommand("insertUnorderedList");
          }}
        >
          <ListIcon size={14} />
        </RichToolbarButton>

        <RichToolbarButton
          title="Numbered list"
          active={formats.insertOrderedList}
          onMouseDown={(e) => {
            e.preventDefault();
            runCommand("insertOrderedList");
          }}
        >
          <OrderedListIcon size={14} />
        </RichToolbarButton>

        <RichToolbarButton
          title="Paragraph"
          onMouseDown={(e) => {
            e.preventDefault();
            runCommand("formatBlock", "p");
          }}
        >
          <span style={{ fontSize: 11, fontWeight: 700 }}>P</span>
        </RichToolbarButton>
      </div>

      <div style={{ position: "relative" }}>
        {isEmpty && !focused && (
          <div
            style={{
              position: "absolute",
              left: 12,
              top: 12,
              color: "#9ca3af",
              pointerEvents: "none",
              fontSize: 14,
            }}
          >
            {placeholder}
          </div>
        )}

        <div
          ref={editorRef}
          contentEditable
          suppressContentEditableWarning
          onFocus={() => {
            setFocused(true);
            updateFormats();
          }}
          onBlur={() => {
            setFocused(false);
            emitChange();
          }}
          onInput={handleInput}
          onKeyUp={updateFormats}
          onMouseUp={updateFormats}
          onPaste={handlePaste}
          style={{
            minHeight: 120,
            padding: 12,
            outline: "none",
            lineHeight: 1.5,
            fontSize: 14,
          }}
        />
      </div>
    </div>
  );
}

function InsertAtBorderButton({ position = "top", onInsert }) {
  const [open, setOpen] = useState(false);
  const [hovered, setHovered] = useState(false);
  const [selectedType, setSelectedType] = useState(SURVEY_QUESTION_TYPES.TEXT);
  const wrapRef = useRef(null);

  useEffect(() => {
    function handleClickOutside(e) {
      if (wrapRef.current && !wrapRef.current.contains(e.target)) {
        setOpen(false);
      }
    }

    function handleEscape(e) {
      if (e.key === "Escape") setOpen(false);
    }

    document.addEventListener("mousedown", handleClickOutside);
    document.addEventListener("keydown", handleEscape);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
      document.removeEventListener("keydown", handleEscape);
    };
  }, []);

  const isTop = position === "top";
  const isActive = hovered || open;

  return (
    <div
      ref={wrapRef}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{
        position: "absolute",
        left: "50%",
        transform: "translateX(-50%)",
        top: isTop ? -11 : "auto",
        bottom: !isTop ? -11 : "auto",
        zIndex: 6,
        pointerEvents: "auto",
      }}
    >
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        title={isTop ? "Insert above" : "Insert below"}
        style={{
          width: 22,
          height: 22,
          borderRadius: 999,
          border: "1px solid #d1d5db",
          background: "#fff",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          cursor: "pointer",
          padding: 0,
          boxShadow: isActive ? "0 1px 4px rgba(0,0,0,0.10)" : "none",
          opacity: isActive ? 1 : 0.4,
          transition:
            "opacity 0.15s ease, box-shadow 0.15s ease, transform 0.15s ease",
          transform: isActive ? "scale(1)" : "scale(0.96)",
        }}
      >
        <PlusIcon size={10} />
      </button>

      {open && (
        <div
          style={{
            position: "absolute",
            left: "50%",
            transform: "translateX(-50%)",
            top: isTop ? 28 : "auto",
            bottom: !isTop ? 28 : "auto",
            minWidth: 220,
            padding: 10,
            borderRadius: 10,
            border: "1px solid #d1d5db",
            background: "#fff",
            boxShadow: "0 10px 24px rgba(0,0,0,0.12)",
          }}
        >
          <div style={{ fontSize: 12, marginBottom: 6 }}>Add question</div>

          <SelectInput value={selectedType} onChange={setSelectedType}>
            {INSERTABLE_TYPES.map((t) => (
              <option key={t} value={t}>
                {QUESTION_TYPE_LABELS[t] || t}
              </option>
            ))}
          </SelectInput>

          <button
            type="button"
            onClick={() => {
              onInsert(selectedType);
              setOpen(false);
            }}
            style={{
              marginTop: 8,
              width: "100%",
              padding: "6px 8px",
              borderRadius: 6,
              border: "1px solid #d1d5db",
              background: "#fff",
              cursor: "pointer",
            }}
          >
            Add
          </button>
        </div>
      )}
    </div>
  );
}

function ItemTableEditor({
  title,
  items,
  onChange,
  prefix = "opt",
  addLabel = "Add row",
  valuePlaceholder = "Value",
  labelPlaceholder = "Label",
}) {
  const safeItems = Array.isArray(items) ? items : [];

  function updateItem(index, patch) {
    onChange(safeItems.map((item, i) => (i === index ? { ...item, ...patch } : item)));
  }

  function addItem() {
    const nextValue =
      prefix === "opt" || prefix === "col"
        ? makeNumericValue(safeItems.length)
        : makeSequentialValue(prefix, safeItems.length);

    onChange([
      ...safeItems,
      {
        value: nextValue,
        label: "",
      },
    ]);
  }

  function removeItem(index) {
    onChange(safeItems.filter((_, i) => i !== index));
  }

  const singularTitle =
    String(title || "item")
      .replace(/ \/ .*/g, "")
      .replace(/s$/i, "")
      .toLowerCase() || "item";

  return (
    <div
      style={{
        border: "1px solid #d1d5db",
        borderRadius: 10,
        padding: 10,
        background: "#fafafa",
      }}
    >
      <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 8 }}>{title}</div>

      {safeItems.length === 0 && (
        <div style={{ fontSize: 12, color: "#6b7280", marginBottom: 8 }}>
          No items yet.
        </div>
      )}

      <div style={{ display: "grid", gap: 8 }}>
        {safeItems.map((item, i) => (
          <div
            key={`${prefix}_${i}`}
            style={{
              display: "grid",
              gridTemplateColumns: "160px 1fr auto",
              gap: 8,
              alignItems: "center",
            }}
          >
            <TextInput
              value={item?.value ?? ""}
              onChange={(v) => updateItem(i, { value: v })}
              placeholder={valuePlaceholder}
            />
            <TextInput
              value={item?.label ?? ""}
              onChange={(v) => updateItem(i, { label: v })}
              placeholder={labelPlaceholder}
            />
            <IconOnlyButton
              onClick={() => removeItem(i)}
              title={`Delete ${singularTitle}`}
              danger
            />
          </div>
        ))}
      </div>

      <button
        type="button"
        onClick={addItem}
        style={{
          marginTop: 10,
          padding: "8px 10px",
          borderRadius: 8,
          border: "1px solid #d1d5db",
          background: "#fff",
          cursor: "pointer",
        }}
      >
        + {addLabel}
      </button>
    </div>
  );
}

function BipolarRowTableEditor({ items, onChange, questionId }) {
  const safeItems = Array.isArray(items) ? items : [];

  function updateItem(index, patch) {
    onChange(safeItems.map((item, i) => (i === index ? { ...item, ...patch } : item)));
  }

  function addItem() {
    onChange([
      ...safeItems,
      {
        value: makeMatrixRowValue(questionId, safeItems.length),
        left_label: "",
        right_label: "",
      },
    ]);
  }

  function removeItem(index) {
    onChange(safeItems.filter((_, i) => i !== index));
  }

  return (
    <div
      style={{
        border: "1px solid #d1d5db",
        borderRadius: 10,
        padding: 10,
        background: "#fafafa",
      }}
    >
      <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 8 }}>
        Rows / bipolar anchors
      </div>

      {safeItems.length === 0 && (
        <div style={{ fontSize: 12, color: "#6b7280", marginBottom: 8 }}>
          No rows yet.
        </div>
      )}

      <div style={{ display: "grid", gap: 8 }}>
        {safeItems.map((item, i) => (
          <div
            key={`bipolar_row_${i}`}
            style={{
              display: "grid",
              gridTemplateColumns: "160px 1fr 1fr auto",
              gap: 8,
              alignItems: "center",
            }}
          >
            <TextInput
              value={item?.value ?? ""}
              onChange={(v) => updateItem(i, { value: v })}
              placeholder="Value"
            />
            <TextInput
              value={item?.left_label ?? ""}
              onChange={(v) => updateItem(i, { left_label: v })}
              placeholder="Left label"
            />
            <TextInput
              value={item?.right_label ?? ""}
              onChange={(v) => updateItem(i, { right_label: v })}
              placeholder="Right label"
            />
            <IconOnlyButton onClick={() => removeItem(i)} title="Delete row" danger />
          </div>
        ))}
      </div>

      <button
        type="button"
        onClick={addItem}
        style={{
          marginTop: 10,
          padding: "8px 10px",
          borderRadius: 8,
          border: "1px solid #d1d5db",
          background: "#fff",
          cursor: "pointer",
        }}
      >
        + Add row
      </button>
    </div>
  );
}

function FeedVisibilityEditor({ availableFeeds, value, onChange }) {
  const safeFeeds = Array.isArray(availableFeeds) ? availableFeeds : [];
  const selected = new Set(normalizeVisibleInFeeds(value));

  function toggleFeed(feedId) {
    const next = new Set(selected);
    if (next.has(feedId)) next.delete(feedId);
    else next.add(feedId);
    onChange(Array.from(next));
  }

  function selectAll() {
    onChange(safeFeeds.map((f) => String(f.feed_id || "")).filter(Boolean));
  }

  function clearSelection() {
    onChange([]);
  }

  if (safeFeeds.length === 0) {
    return (
      <div
        style={{
          border: "1px solid #d1d5db",
          borderRadius: 10,
          padding: 12,
          background: "#fafafa",
          color: "#6b7280",
          fontSize: 13,
        }}
      >
        Link the survey to feeds first. Question-level feed visibility becomes available once the
        survey has linked feeds.
      </div>
    );
  }

  return (
    <div
      style={{
        border: "1px solid #d1d5db",
        borderRadius: 10,
        padding: 12,
        background: "#fafafa",
      }}
    >
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          gap: 12,
          marginBottom: 10,
          flexWrap: "wrap",
        }}
      >
        <div style={{ fontSize: 13, color: "#111827" }}>
          If no feeds are selected, this question is shown in all linked feeds.
        </div>

        <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
          <button
            type="button"
            onClick={selectAll}
            style={{
              padding: "6px 10px",
              borderRadius: 8,
              border: "1px solid #d1d5db",
              background: "#fff",
              cursor: "pointer",
              fontSize: 12,
              fontWeight: 600,
            }}
          >
            Select all
          </button>

          <button
            type="button"
            onClick={clearSelection}
            style={{
              padding: "6px 10px",
              borderRadius: 8,
              border: "1px solid #d1d5db",
              background: "#fff",
              cursor: "pointer",
              fontSize: 12,
              fontWeight: 600,
            }}
          >
            Show in all
          </button>
        </div>
      </div>

      <div style={{ display: "grid", gap: 8 }}>
        {safeFeeds.map((feed) => {
          const feedId = String(feed?.feed_id || "").trim();
          if (!feedId) return null;

          return (
            <label
              key={feedId}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 8,
                cursor: "pointer",
                padding: "6px 2px",
              }}
            >
              <input
                type="checkbox"
                checked={selected.has(feedId)}
                onChange={() => toggleFeed(feedId)}
              />
              <span>{feed?.name || feedId}</span>
            </label>
          );
        })}
      </div>
    </div>
  );
}

function FeedOverridesEditor({ availableFeeds, value, onChange }) {
  const safeFeeds = Array.isArray(availableFeeds) ? availableFeeds : [];
  const normalized = normalizeFeedOverridesMap(value);

  function updateFeedText(feedId, nextText) {
    const next = {
      ...normalized,
      [feedId]: {
        ...(normalized[feedId] || {}),
        text: normalizeRichTextHtml(nextText ?? ""),
      },
    };

    onChange(next);
  }

  if (safeFeeds.length === 0) {
    return (
      <div
        style={{
          border: "1px solid #d1d5db",
          borderRadius: 10,
          padding: 12,
          background: "#fafafa",
          color: "#6b7280",
          fontSize: 13,
        }}
      >
        No linked feeds available for feed-specific question text yet.
      </div>
    );
  }

  return (
    <div
      style={{
        border: "1px solid #d1d5db",
        borderRadius: 10,
        padding: 12,
        background: "#fafafa",
      }}
    >
      <div style={{ fontSize: 13, color: "#111827", marginBottom: 10 }}>
        Leave a field blank to use the default question text.
      </div>

      <div style={{ display: "grid", gap: 14 }}>
        {safeFeeds.map((feed) => {
          const feedId = String(feed?.feed_id || "").trim();
          if (!feedId) return null;

          return (
            <div
              key={feedId}
              style={{
                display: "grid",
                gap: 8,
              }}
            >
              <div style={{ fontSize: 13, fontWeight: 600, color: "#111827" }}>
                {feed?.name || feedId}
              </div>

              <RichTextEditor
                value={normalized?.[feedId]?.text ?? ""}
                onChange={(v) => updateFeedText(feedId, v)}
                placeholder="Alternative question text for this feed"
              />
            </div>
          );
        })}
      </div>
    </div>
  );
}

function PostReminderEditor({
  availablePosts,
  value,
  label,
  selectedFeedIds = [],
  onChange,
}) {
  const safePosts = Array.isArray(availablePosts) ? availablePosts : [];
  const hasRelevantFeeds = Array.isArray(selectedFeedIds) && selectedFeedIds.length > 0;

  if (!hasRelevantFeeds) {
    return (
      <div
        style={{
          border: "1px solid #d1d5db",
          borderRadius: 10,
          padding: 12,
          background: "#fafafa",
          color: "#6b7280",
          fontSize: 13,
        }}
      >
        Link this survey to feeds first. Then you can choose which linked-feed post should be shown
        again in the survey.
      </div>
    );
  }

  if (safePosts.length === 0) {
    return (
      <div
        style={{
          border: "1px solid #d1d5db",
          borderRadius: 10,
          padding: 12,
          background: "#fafafa",
          color: "#6b7280",
          fontSize: 13,
        }}
      >
        No posts were found in the relevant linked feed(s). Save or load posts in those feeds first,
        then choose which one should be shown again in the survey.
      </div>
    );
  }

  return (
    <div
      style={{
        border: "1px solid #d1d5db",
        borderRadius: 10,
        padding: 12,
        background: "#fafafa",
      }}
    >
      <SelectInput
        value={value || ""}
        onChange={(nextPostId) => {
          const selectedPost = safePosts.find(
            (post) => String(post?.id || "") === String(nextPostId)
          );

          onChange({
            post_id: String(nextPostId || ""),
            post_label: nextPostId ? String(selectedPost?._option_label || "") : "",
            post_feed_id: nextPostId ? String(selectedPost?._feed_id || "") : "",
            meta: {
              post_feed_id: nextPostId ? String(selectedPost?._feed_id || "") : "",
            },
          });
        }}
      >
        <option value="">Select a post</option>
        {safePosts.map((post, postIndex) => {
          const postId = String(post?.id || "").trim();
          if (!postId) return null;

          return (
            <option key={`${post._feed_id || "feed"}::${postId}`} value={postId}>
              {post._option_label || derivePostOptionLabel(post, postIndex, post?._feed_name || "")}
            </option>
          );
        })}
      </SelectInput>

      {value ? (
        <div style={{ marginTop: 8, fontSize: 12, color: "#6b7280" }}>
          Selected: {label || value}
        </div>
      ) : null}
    </div>
  );
}

function QuestionAdvancedFeedTools({
  q,
  linkedFeeds,
  onToggleVisibilityEditor,
  onToggleOverridesEditor,
}) {
  const visibleFeedCount = normalizeVisibleInFeeds(q?.visible_in_feeds).length;
  const overrideCount = Object.keys(pruneFeedOverridesMap(q?.feed_overrides)).length;
  const hasLinkedFeeds = Array.isArray(linkedFeeds) && linkedFeeds.length > 0;

  return (
    <div
      style={{
        marginTop: 14,
        display: "flex",
        gap: 8,
        flexWrap: "wrap",
        alignItems: "center",
      }}
    >
      <SecondaryPillButton
        onClick={onToggleVisibilityEditor}
        active={!!q?._showFeedVisibilityEditor}
        title="Question display by linked feed"
        disabled={!hasLinkedFeeds}
      >
        <EyeIcon size={14} />
        <span>
          Display logic
          {visibleFeedCount > 0 ? ` (${visibleFeedCount})` : ""}
        </span>
        <ChevronDownIcon size={12} open={!!q?._showFeedVisibilityEditor} />
      </SecondaryPillButton>

      <SecondaryPillButton
        onClick={onToggleOverridesEditor}
        active={!!q?._showFeedOverridesEditor}
        title="Alternative question text by linked feed"
        disabled={!hasLinkedFeeds}
      >
        <TextCursorIcon size={14} />
        <span>
          Alternative text
          {overrideCount > 0 ? ` (${overrideCount})` : ""}
        </span>
        <ChevronDownIcon size={12} open={!!q?._showFeedOverridesEditor} />
      </SecondaryPillButton>

      {!hasLinkedFeeds && (
        <span style={{ fontSize: 12, color: "#6b7280" }}>
          Link this survey to feeds first.
        </span>
      )}
    </div>
  );
}

/* =========================
   Question editor
   ========================= */

function QuestionActions({
  q,
  index,
  totalQuestions,
  moveQuestion,
  removeQuestion,
  duplicateQuestion,
  updateQuestion,
  onDragStart,
  onDragEnd,
}) {
  const isDisplayOnly = isEditorDisplayOnlyType(q?.type);

  return (
    <TopField label="Actions">
      <div
        style={{
          display: "flex",
          gap: 6,
          alignItems: "center",
          height: INPUT_HEIGHT,
        }}
      >
        <DragHandle
          onDragStart={(e) => onDragStart(e, q._editorId)}
          onDragEnd={onDragEnd}
        />

        {!isDisplayOnly && (
          <RequiredToggleButton
            active={!!q.required}
            onClick={() => updateQuestion(index, { required: !q.required })}
          />
        )}

        <button
          type="button"
          onClick={() => moveQuestion(index, index - 1)}
          disabled={index === 0}
          style={smallActionButtonStyle(index === 0)}
        >
          ↑
        </button>

        <button
          type="button"
          onClick={() => moveQuestion(index, index + 1)}
          disabled={index === totalQuestions - 1}
          style={smallActionButtonStyle(index === totalQuestions - 1)}
        >
          ↓
        </button>

        <IconOnlyButton onClick={() => duplicateQuestion(index)} title="Copy question">
          <CopyIcon size={16} />
        </IconOnlyButton>

        <IconOnlyButton
          onClick={() => removeQuestion(index)}
          title="Delete question"
          danger
        />
      </div>
    </TopField>
  );
}

function QuestionCard({
  q,
  index,
  displayNumber,
  totalQuestions,
  linkedFeeds,
  linkedFeedPostsMap,
  updateQuestion,
  removeQuestion,
  moveQuestion,
  duplicateQuestion,
  insertQuestionAt,
  draggingId,
  dragOverId,
  onDragStart,
  onDragOver,
  onDrop,
  onDragEnd,
}) {
  const type = q?.type;
  const isPageBreak = type === EDITOR_PAGE_BREAK_TYPE;

  const isChoice =
    type === SURVEY_QUESTION_TYPES.SINGLE ||
    type === SURVEY_QUESTION_TYPES.MULTI ||
    type === SURVEY_QUESTION_TYPES.DROPDOWN;

  const isMatrix =
    type === SURVEY_QUESTION_TYPES.MATRIX_SINGLE ||
    type === SURVEY_QUESTION_TYPES.MATRIX_MULTI;

  const isBipolar = type === SURVEY_QUESTION_TYPES.BIPOLAR;
  const isSlider = type === SURVEY_QUESTION_TYPES.SLIDER;
  const isPostReminder = type === POST_REMINDER_TYPE;

  const isDragging = draggingId === q._editorId;
  const isDragOver = dragOverId === q._editorId;

  const scopedFeedIds = normalizeVisibleInFeeds(q?.visible_in_feeds);
  const scopedFeeds = Array.isArray(linkedFeeds)
    ? linkedFeeds.filter((feed) =>
        scopedFeedIds.includes(String(feed?.feed_id || "").trim())
      )
    : [];

  const hasFeedVisibilitySelection = scopedFeedIds.length > 0;
  const safeOverrideFeeds = hasFeedVisibilitySelection ? scopedFeeds : linkedFeeds;

  const reminderFeedIds = getRelevantFeedIdsForQuestion(q, linkedFeeds);
  const availablePostsForQuestion = getAvailablePostsForQuestion(
    q,
    linkedFeeds,
    linkedFeedPostsMap
  );

  const shellStyle = {
    position: "relative",
    border: isDragOver
      ? "2px solid #6366f1"
      : `1px solid ${isPageBreak ? "#9ca3af" : "#d1d5db"}`,
    borderStyle: isPageBreak ? "dashed" : "solid",
    borderRadius: 12,
    padding: 14,
    marginTop: 18,
    marginBottom: 26,
    background: isDragging ? "#f8fafc" : isPageBreak ? "#f9fafb" : "#fff",
    opacity: isDragging ? 0.65 : 1,
    boxShadow: isDragOver ? "0 0 0 3px rgba(99,102,241,0.12)" : "none",
  };

  if (isPageBreak) {
    return (
      <div
        onDragOver={(e) => onDragOver(e, q._editorId)}
        onDrop={(e) => onDrop(e, q._editorId)}
        style={shellStyle}
      >
        <InsertAtBorderButton
          position="top"
          onInsert={(nextType) => insertQuestionAt(index, nextType, "above")}
        />
        <InsertAtBorderButton
          position="bottom"
          onInsert={(nextType) => insertQuestionAt(index, nextType, "below")}
        />

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr auto",
            gap: 10,
            alignItems: "start",
          }}
        >
          <TopField label="Page break">
            <div
              style={{
                height: INPUT_HEIGHT,
                display: "flex",
                alignItems: "center",
                padding: "0 12px",
                border: "1px solid #d1d5db",
                borderRadius: 8,
                background: "#fff",
                color: "#6b7280",
              }}
            >
              Questions after this will appear on the next page.
            </div>
          </TopField>

          <TopField label="Actions">
            <div
              style={{
                display: "flex",
                gap: 6,
                alignItems: "center",
                height: INPUT_HEIGHT,
              }}
            >
              <DragHandle
                onDragStart={(e) => onDragStart(e, q._editorId)}
                onDragEnd={onDragEnd}
              />

              <button
                type="button"
                onClick={() => moveQuestion(index, index - 1)}
                disabled={index === 0}
                style={smallActionButtonStyle(index === 0)}
              >
                ↑
              </button>

              <button
                type="button"
                onClick={() => moveQuestion(index, index + 1)}
                disabled={index === totalQuestions - 1}
                style={smallActionButtonStyle(index === totalQuestions - 1)}
              >
                ↓
              </button>

              <IconOnlyButton
                onClick={() => removeQuestion(index)}
                title="Delete page break"
                danger
              />
            </div>
          </TopField>
        </div>
      </div>
    );
  }

  return (
    <div
      onDragOver={(e) => onDragOver(e, q._editorId)}
      onDrop={(e) => onDrop(e, q._editorId)}
      style={shellStyle}
    >
      <InsertAtBorderButton
        position="top"
        onInsert={(nextType) => insertQuestionAt(index, nextType, "above")}
      />
      <InsertAtBorderButton
        position="bottom"
        onInsert={(nextType) => insertQuestionAt(index, nextType, "below")}
      />

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "minmax(0,1fr) 220px auto",
          gap: 10,
          alignItems: "start",
          marginBottom: 10,
        }}
      >
        <TopField
          label={
            isEditorDisplayOnlyType(type)
              ? QUESTION_TYPE_LABELS[type] || "Display block"
              : `Question ${displayNumber}`
          }
        >
          <RichTextEditor
            value={q.text || ""}
            onChange={(v) => updateQuestion(index, { text: v })}
            placeholder={
              isEditorDisplayOnlyType(type) ? "Display text" : "Question text"
            }
          />
        </TopField>

        <TopField label="Type">
          <SelectInput
            value={q.type}
            onChange={(nextType) => {
              if (nextType === EDITOR_PAGE_BREAK_TYPE) {
                updateQuestion(index, makePageBreakForEditor(index));
                return;
              }

              const next = makeBackendQuestionFromType(nextType, index);
              const preservedId = sanitizeQuestionId(q.id, next.id);

              let merged = {
                ...next,
                _editorId: q._editorId,
                id: preservedId,
                text: q.text || next.text,
                required: isEditorDisplayOnlyType(nextType)
                  ? false
                  : !!q.required,
                visible_if: q.visible_if || null,
                visible_in_feeds: normalizeVisibleInFeeds(q.visible_in_feeds),
                feed_overrides: normalizeFeedOverridesMap(q.feed_overrides),
                post_id: nextType === POST_REMINDER_TYPE ? String(q.post_id || "") : "",
                post_label:
                  nextType === POST_REMINDER_TYPE ? String(q.post_label || "") : "",
                post_feed_id:
                  nextType === POST_REMINDER_TYPE
                    ? String(q.post_feed_id || "")
                    : "",
                _showFeedVisibilityEditor: !!q._showFeedVisibilityEditor,
                _showFeedOverridesEditor: !!q._showFeedOverridesEditor,
                meta: q.meta || {},
              };

              if (shouldAutoRewriteRowValues(merged)) {
                merged = rewriteQuestionRowValues(merged, preservedId);
              }

              updateQuestion(index, merged);
            }}
          >
            {INSERTABLE_TYPES.map((t) => (
              <option key={t} value={t}>
                {QUESTION_TYPE_LABELS[t] || t}
              </option>
            ))}
          </SelectInput>
        </TopField>

        <QuestionActions
          q={q}
          index={index}
          totalQuestions={totalQuestions}
          moveQuestion={moveQuestion}
          removeQuestion={removeQuestion}
          duplicateQuestion={duplicateQuestion}
          updateQuestion={updateQuestion}
          onDragStart={onDragStart}
          onDragEnd={onDragEnd}
        />
      </div>

      <FieldBlock label="Question ID / variable name">
        <TextInput
          value={q.id || ""}
          onChange={(v) => {
            const cleanedId = sanitizeQuestionId(v, "");
            let nextQuestion = {
              ...q,
              id: cleanedId,
            };

            if (cleanedId && shouldAutoRewriteRowValues(nextQuestion)) {
              nextQuestion = rewriteQuestionRowValues(nextQuestion, cleanedId);
            }

            updateQuestion(index, nextQuestion);
          }}
          placeholder="e.g. AUTH"
        />
      </FieldBlock>

      {isPostReminder && (
        <FieldBlock
          label="Post to show again"
          hint="This will display the selected linked-feed post again in the survey as a non-interactive reminder."
        >
          <PostReminderEditor
            availablePosts={availablePostsForQuestion}
            selectedFeedIds={reminderFeedIds}
            value={q.post_id}
            label={q.post_label}
            onChange={(patch) => updateQuestion(index, patch)}
          />
        </FieldBlock>
      )}

      {isChoice && (
        <ItemTableEditor
          title="Options"
          items={q.choices}
          onChange={(items) =>
            updateQuestion(index, { choices: ensureChoiceArray(items) })
          }
          prefix="opt"
          addLabel="Add option"
        />
      )}

      {isMatrix && (
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr",
            gap: 12,
          }}
        >
          <ItemTableEditor
            title="Rows / items"
            items={q.rows}
            onChange={(items) =>
              updateQuestion(index, {
                rows: ensureMatrixRowsFromQuestionId(items, q.id),
              })
            }
            prefix={sanitizeQuestionId(q.id, "ROW")}
            addLabel="Add row"
            valuePlaceholder="Auto id"
            labelPlaceholder="Item text"
          />

          <ItemTableEditor
            title="Columns / scale points"
            items={q.columns}
            onChange={(items) =>
              updateQuestion(index, { columns: ensureMatrixArray(items, "col") })
            }
            prefix="col"
            addLabel="Add column"
            valuePlaceholder="Value"
            labelPlaceholder="Label"
          />
        </div>
      )}

      {isBipolar && (
        <>
          <div style={{ marginBottom: 12 }}>
            <BipolarRowTableEditor
              items={q.rows}
              questionId={q.id}
              onChange={(items) =>
                updateQuestion(index, {
                  rows: ensureBipolarRowArray(items, q.id),
                })
              }
            />
          </div>

          <div
            style={{
              display: "grid",
              gridTemplateColumns: "120px 120px",
              gap: 12,
              alignItems: "end",
            }}
          >
            <FieldBlock label="Min">
              <NumberInput
                value={q.min}
                min={1}
                max={100}
                onChange={(v) =>
                  updateQuestion(index, {
                    min: clampInt(v, 1, 100, q.min ?? 1),
                  })
                }
              />
            </FieldBlock>

            <FieldBlock label="Max">
              <NumberInput
                value={q.max}
                min={2}
                max={100}
                onChange={(v) =>
                  updateQuestion(index, {
                    max: clampInt(v, 2, 100, q.max ?? 7),
                  })
                }
              />
            </FieldBlock>
          </div>
        </>
      )}

      {isSlider && (
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "120px 120px 1fr 1fr",
            gap: 12,
            alignItems: "end",
          }}
        >
          <FieldBlock label="Min">
            <NumberInput
              value={q.min}
              min={0}
              max={100}
              onChange={(v) =>
                updateQuestion(index, {
                  min: clampInt(v, 0, 100, q.min ?? 1),
                })
              }
            />
          </FieldBlock>

          <FieldBlock label="Max">
            <NumberInput
              value={q.max}
              min={1}
              max={100}
              onChange={(v) =>
                updateQuestion(index, {
                  max: clampInt(v, 1, 100, q.max ?? 7),
                })
              }
            />
          </FieldBlock>

          <FieldBlock label="Left label">
            <TextInput
              value={q.left_label ?? ""}
              onChange={(v) => updateQuestion(index, { left_label: v })}
              placeholder="e.g. Low"
            />
          </FieldBlock>

          <FieldBlock label="Right label">
            <TextInput
              value={q.right_label ?? ""}
              onChange={(v) => updateQuestion(index, { right_label: v })}
              placeholder="e.g. High"
            />
          </FieldBlock>
        </div>
      )}

      <QuestionAdvancedFeedTools
        q={q}
        linkedFeeds={linkedFeeds}
        onToggleVisibilityEditor={() =>
          updateQuestion(index, {
            _showFeedVisibilityEditor: !q?._showFeedVisibilityEditor,
          })
        }
        onToggleOverridesEditor={() =>
          updateQuestion(index, {
            _showFeedOverridesEditor: !q?._showFeedOverridesEditor,
          })
        }
      />

      {q?._showFeedVisibilityEditor && (
        <div style={{ marginTop: 12 }}>
          <FieldBlock
            label="Feed visibility"
            hint="Restrict this question to selected linked feeds. Leaving all unchecked means it will show in all linked feeds."
          >
            <FeedVisibilityEditor
              availableFeeds={linkedFeeds}
              value={q.visible_in_feeds}
              onChange={(nextVisibleInFeeds) => {
                const normalizedVisibleFeeds =
                  normalizeVisibleInFeeds(nextVisibleInFeeds);
                const prunedOverrides = pruneFeedOverridesMap(
                  q.feed_overrides,
                  normalizedVisibleFeeds
                );

                updateQuestion(index, {
                  visible_in_feeds: normalizedVisibleFeeds,
                  feed_overrides: prunedOverrides,
                });
              }}
            />
          </FieldBlock>
        </div>
      )}

      {q?._showFeedOverridesEditor && (
        <div style={{ marginTop: 12 }}>
          <FieldBlock
            label="Feed-specific question text"
            hint={
              hasFeedVisibilitySelection
                ? "These alternative texts apply to the currently selected display-logic feeds."
                : "Optional alternative text shown for linked feeds. Leave a field blank to use the default question text."
            }
          >
            <FeedOverridesEditor
              availableFeeds={safeOverrideFeeds}
              value={q.feed_overrides}
              onChange={(nextOverrides) =>
                updateQuestion(index, {
                  feed_overrides: pruneFeedOverridesMap(
                    nextOverrides,
                    hasFeedVisibilitySelection
                      ? normalizeVisibleInFeeds(q.visible_in_feeds)
                      : []
                  ),
                })
              }
            />
          </FieldBlock>
        </div>
      )}
    </div>
  );
}

function smallActionButtonStyle(disabled) {
  return {
    width: INPUT_HEIGHT,
    height: INPUT_HEIGHT,
    borderRadius: 8,
    border: "1px solid #d1d5db",
    background: "#fff",
    color: disabled ? "#9ca3af" : "#111827",
    cursor: disabled ? "not-allowed" : "pointer",
    padding: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flex: "0 0 auto",
  };
}

/* =========================
   Main editor component
   ========================= */

export function SurveyEditor({
  survey,
  onSurveyChange,
  linkedFeeds = [],
  linkedFeedPostsMap = {},
}) {
  const [draggingQuestionId, setDraggingQuestionId] = useState(null);
  const [dragOverQuestionId, setDragOverQuestionId] = useState(null);

  const currentQuestions = useMemo(() => getQuestionList(survey), [survey]);

  const questionDisplayNumbers = useMemo(() => {
    let count = 0;
    return currentQuestions.map((item) => {
      if (isCountedQuestionType(item?.type)) {
        count += 1;
        return count;
      }
      return null;
    });
  }, [currentQuestions]);

  function addQuestion(type) {
    onSurveyChange((prev) => {
      const current = getQuestionList(prev);
      return setQuestionList(prev, [
        ...current,
        makeBackendQuestionFromType(type, current.length),
      ]);
    });
  }

  function insertQuestionAt(index, type, position = "below") {
    onSurveyChange((prev) => {
      const current = getQuestionList(prev);
      const insertIndex = position === "above" ? index : index + 1;
      const nextQuestions = [...current];
      nextQuestions.splice(
        insertIndex,
        0,
        makeBackendQuestionFromType(type, insertIndex)
      );
      return setQuestionList(prev, nextQuestions);
    });
  }

  function duplicateQuestion(index) {
    onSurveyChange((prev) => {
      const currentQuestionsCopy = [...getQuestionList(prev)];
      const sourceQuestion = currentQuestionsCopy[index];

      if (!sourceQuestion) return prev;

      const existingIds = currentQuestionsCopy
        .filter((q) => q?.type !== EDITOR_PAGE_BREAK_TYPE)
        .map((q) => q?.id)
        .filter(Boolean);

      const nextId = makeCopiedQuestionId(existingIds, sourceQuestion.id);

      let copiedQuestion = {
        ...sourceQuestion,
        _editorId: makeEditorId(),
        id: nextId,
        meta: sourceQuestion?.meta ? { ...sourceQuestion.meta } : {},
        visible_if: sourceQuestion?.visible_if
          ? JSON.parse(JSON.stringify(sourceQuestion.visible_if))
          : null,
        visible_in_feeds: normalizeVisibleInFeeds(
          sourceQuestion?.visible_in_feeds
        ),
        feed_overrides: normalizeFeedOverridesMap(
          sourceQuestion?.feed_overrides
        ),
        post_id: String(sourceQuestion?.post_id ?? ""),
        post_label: String(sourceQuestion?.post_label ?? ""),
        post_feed_id: String(sourceQuestion?.post_feed_id ?? ""),
        _showFeedVisibilityEditor: !!sourceQuestion?._showFeedVisibilityEditor,
        _showFeedOverridesEditor: !!sourceQuestion?._showFeedOverridesEditor,
      };

      if (shouldAutoRewriteRowValues(copiedQuestion)) {
        copiedQuestion = rewriteQuestionRowValues(copiedQuestion, nextId);
      }

      copiedQuestion = normalizeQuestionForEditor(copiedQuestion, index + 1);

      currentQuestionsCopy.splice(index + 1, 0, copiedQuestion);
      return setQuestionList(prev, currentQuestionsCopy);
    });
  }

  function updateQuestion(index, patch) {
    onSurveyChange((prev) => {
      const currentQuestionsCopy = [...getQuestionList(prev)];
      const currentQuestion = currentQuestionsCopy[index] || {};
      const merged =
        patch && typeof patch === "object" && !Array.isArray(patch)
          ? { ...currentQuestion, ...patch }
          : currentQuestion;

      currentQuestionsCopy[index] = normalizeQuestionForEditor(merged, index);
      return setQuestionList(prev, currentQuestionsCopy);
    });
  }

  function removeQuestion(index) {
    onSurveyChange((prev) => {
      const currentQuestionsCopy = [...getQuestionList(prev)];
      currentQuestionsCopy.splice(index, 1);
      return setQuestionList(prev, currentQuestionsCopy);
    });
  }

  function moveQuestion(fromIndex, toIndex) {
    onSurveyChange((prev) => {
      const current = getQuestionList(prev);
      const reordered = reorderArray(current, fromIndex, toIndex);
      return setQuestionList(prev, reordered);
    });
  }

  function handleQuestionDragStart(e, questionId) {
    setDraggingQuestionId(questionId);
    setDragOverQuestionId(questionId);
    try {
      e.dataTransfer.effectAllowed = "move";
      e.dataTransfer.setData("text/plain", String(questionId));
    } catch {}
  }

  function handleQuestionDragOver(e, questionId) {
    e.preventDefault();
    try {
      e.dataTransfer.dropEffect = "move";
    } catch {}
    if (dragOverQuestionId !== questionId) {
      setDragOverQuestionId(questionId);
    }
  }

  function handleQuestionDrop(e, targetQuestionId) {
    e.preventDefault();

    if (!survey || !draggingQuestionId || draggingQuestionId === targetQuestionId) {
      setDraggingQuestionId(null);
      setDragOverQuestionId(null);
      return;
    }

    const questions = getQuestionList(survey);
    const fromIndex = questions.findIndex((q) => q._editorId === draggingQuestionId);
    const toIndex = questions.findIndex((q) => q._editorId === targetQuestionId);

    if (fromIndex >= 0 && toIndex >= 0 && fromIndex !== toIndex) {
      moveQuestion(fromIndex, toIndex);
    }

    setDraggingQuestionId(null);
    setDragOverQuestionId(null);
  }

  function handleQuestionDragEnd() {
    setDraggingQuestionId(null);
    setDragOverQuestionId(null);
  }

  return (
    <SectionCard title="Questions">
      <div style={{ fontSize: 12, color: "#6b7280", marginBottom: 18 }}>
        Drag items by the dotted handle to reorder them. Use the + buttons on the borders
        to insert new questions.
      </div>

      {currentQuestions.map((q, i) => (
        <QuestionCard
          key={q._editorId || i}
          q={q}
          index={i}
          displayNumber={questionDisplayNumbers[i]}
          totalQuestions={currentQuestions.length}
          linkedFeeds={linkedFeeds}
          linkedFeedPostsMap={linkedFeedPostsMap}
          updateQuestion={updateQuestion}
          removeQuestion={removeQuestion}
          moveQuestion={moveQuestion}
          duplicateQuestion={duplicateQuestion}
          insertQuestionAt={insertQuestionAt}
          draggingId={draggingQuestionId}
          dragOverId={dragOverQuestionId}
          onDragStart={handleQuestionDragStart}
          onDragOver={handleQuestionDragOver}
          onDrop={handleQuestionDrop}
          onDragEnd={handleQuestionDragEnd}
        />
      ))}

      {currentQuestions.length === 0 && (
        <div
          style={{
            position: "relative",
            border: "1px dashed #d1d5db",
            borderRadius: 12,
            padding: 28,
            background: "#fff",
            textAlign: "center",
            color: "#6b7280",
          }}
        >
          No questions yet.
          <div style={{ marginTop: 10 }}>
            <InsertAtBorderButton
              position="bottom"
              onInsert={(nextType) => addQuestion(nextType)}
            />
          </div>
        </div>
      )}
    </SectionCard>
  );
}